src/graph.rs, tests/it/can_create_graph.rs, tests/it/can_find_node_partial_paths_in_database.rs, tests/it/can_find_partial_paths_in_file.rs, tests/it/can_find_root_partial_paths_in_database.rs, tests/it/can_jump_to_definition.rs, tests/it/can_jump_to_definition_with_partial_paths.rs, tests/it/test_graphs/class_field_through_function_parameter.rs, tests/it/test_graphs/cyclic_imports_python.rs, tests/it/test_graphs/cyclic_imports_rust.rs, tests/it/test_graphs/mod.rs, tests/it/test_graphs/sequenced_import_star.rs
This will let us create our test graphs using both the Rust and C APIs.
=> Make CreateStackGraph test trait more generic

src/partial.rs
This is a fairly straightforward copy-paste job.
=> Add binding structs for partial scope/symbol stacks.

include/stack-graphs.h, src/c.rs, src/paths.rs, tests/it/c/paths.rs
Very similar to the API for creating scope stacks
=> Add C bindings for creating symbol stacks

include/stack-graphs.h, src/arena.rs, src/c.rs, src/paths.rs, tests/it/c/paths.rs
This requires plumbing through deques and all of their related nonsense.
=> Add C bindings for creating path edges

src/partial.rs
This new function concatenates two partial paths together, producing a new partial path.  The result has all of the “starting state” (start node, preconditions) of the left-hand side, and the “ending state” (end node, postconditions) of the right-hand side.  We have to unify the “middle parts” — the postcondition of the left-hand side and the precondition of the right-hand side.  The result of that unification (if it succeeds) is a set of variable bindings, which we then substitute into the result's pre- and postconditions.
=> Concatenate partial paths

stack-graphs/src/arena.rs
We had already made this change to `Arena`; this patch makes a similar change to `SupplementalArena`.
Before, the first element added to an arena was stored in the first slot in the underlying `Vec` — meaning that it had index 0 within the arena. However, we're using `NonZeroU32` as our handle type, so that we can use the zero value as `None` when working with optional handles.  That meant that we would have to add 1 to the element's index to get its handle.
This works fine in Rust, where we can hide the internal details of the arena, and ensure that the increment/decrement always happens in the public API methods.  In our C bindings, however, it will be nicer if we can use an element's index directly as its handle.  For this to work, we must reserve element 0 in each arena for the value …
=> Allocate an unused entry 0 in supplemental arenas

AUTHORS, lsp-positions/CHANGELOG.md, lsp-positions/Cargo.toml, lsp-positions/README.md, stack-graphs/CHANGELOG.md, stack-graphs/Cargo.toml, stack-graphs/README.md
This adds changelog files to each crate, as well.
=> Release stack-graphs 0.5.0 and lsp-positions 0.2.0

stack-graphs/Cargo.toml, stack-graphs/src/graph.rs, stack-graphs/src/json.rs, stack-graphs/src/lib.rs, stack-graphs/tests/it/arena.rs, stack-graphs/tests/it/json.rs, stack-graphs/tests/it/main.rs, stack-graphs/tests/it/test_graphs/mod.rs, stack-graphs/tests/it/test_graphs/simple.rs
=> Add JSON output

lsp-positions/CHANGELOG.md, lsp-positions/Cargo.toml, lsp-positions/README.md, stack-graphs/Cargo.toml, tree-sitter-stack-graphs/Cargo.toml
- Bump lsp-positions to 0.3.0
- Update changelog
- Update README
=> release lsp positions 0.3.0

tree-sitter-stack-graphs/examples/.gitignore, tree-sitter-stack-graphs/examples/README.md, tree-sitter-stack-graphs/examples/bootstrap, tree-sitter-stack-graphs/examples/nested-scope/stack-graphs.tsg, tree-sitter-stack-graphs/examples/nested-scope/tests/nested-def.py, tree-sitter-stack-graphs/examples/nested-scope/tests/shadowing.py, tree-sitter-stack-graphs/examples/nested-scope/tests/top-level-defs.py, tree-sitter-stack-graphs/examples/run, tree-sitter-stack-graphs/examples/sequential-definitions/stack-graphs.tsg, tree-sitter-stack-graphs/examples/sequential-definitions/tests/shadow-previous-def.py
This adds some working examples of TSG + tests combinations in lieu of a more extensive user guide.
=> Add working examples

.github/workflows/ci.yml
=> Add tests for json features in CI

.github/workflows/ci.yml, .github/workflows/publish-lsp-positions.yml, .github/workflows/publish-stack-graphs.yml, .github/workflows/publish-tree-sitter-stack-graphs.yml, Cargo.toml, languages/README.md, languages/tree-sitter-stack-graphs-typescript/.gitignore, languages/tree-sitter-stack-graphs-typescript/Cargo.toml, languages/tree-sitter-stack-graphs-typescript/README.md, languages/tree-sitter-stack-graphs-typescript/rust/bin.rs, languages/tree-sitter-stack-graphs-typescript/rust/lib.rs, languages/tree-sitter-stack-graphs-typescript/rust/test.rs, languages/tree-sitter-stack-graphs-typescript/src/builtins.cfg, languages/tree-sitter-stack-graphs-typescript/src/stack-graphs.tsg
This PR adds a stub language project for TypeScript, and the Cargo and CI changes to test such projects.
- #146
- ▶️ #140 
- #142
=> Add directory to hold language definitions

tree-sitter-stack-graphs/src/lib.rs
Sometimes it is useful to be able to create a reference or definition, which requires a source node, without the whole node being considered a ref/def. An example are module definitions based on the file path, which would use the top-level node, covering the whole program. Adding the `empty_source_span` attribute collapses the source nodes span to the start.
=> Add empty_span attribute

stack-graphs/CHANGELOG.md, stack-graphs/src/assert.rs, tree-sitter-stack-graphs/src/test.rs, tree-sitter-stack-graphs/tests/it/test.rs
=> Add defines and refers assertions

stack-graphs/CHANGELOG.md, stack-graphs/src/graph.rs, stack-graphs/tests/it/c/can_find_local_nodes.rs, stack-graphs/tests/it/c/can_find_partial_paths_in_file.rs, stack-graphs/tests/it/c/can_jump_to_definition_with_phased_partial_path_stitching.rs, stack-graphs/tests/it/c/can_jump_to_definition_with_phased_path_stitching.rs, stack-graphs/tests/it/can_find_local_nodes.rs, stack-graphs/tests/it/can_find_node_partial_paths_in_database.rs, stack-graphs/tests/it/can_find_partial_paths_in_file.rs, stack-graphs/tests/it/can_find_root_partial_paths_in_database.rs, stack-graphs/tests/it/graph.rs
=> Replace `get_file_unchecked` with `get_file`

languages/tree-sitter-stack-graphs-java/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-java/test/decl/class_extension.java, languages/tree-sitter-stack-graphs-java/test/decl/enum_switches.java, languages/tree-sitter-stack-graphs-java/test/decl/interface.java
Adds tests and rules for Java tssg for enum switches, interfaces, and updated class extension tests.
=> Update Java tssg for enum switches, interfaces, class extension

languages/tree-sitter-stack-graphs-java/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-java/test/statement/break.java, languages/tree-sitter-stack-graphs-java/test/statement/continue.java
This PR adds definitions & references for labels.
=> Java: Define & reference labels

stack-graphs/src/graph.rs
=> Update `get_file` documentation

tree-sitter-stack-graphs/src/cli.rs, tree-sitter-stack-graphs/src/cli/clean.rs, tree-sitter-stack-graphs/src/cli/database.rs, tree-sitter-stack-graphs/src/cli/index.rs, tree-sitter-stack-graphs/src/cli/init.rs, tree-sitter-stack-graphs/src/cli/load.rs, tree-sitter-stack-graphs/src/cli/parse.rs, tree-sitter-stack-graphs/src/cli/query.rs, tree-sitter-stack-graphs/src/cli/status.rs, tree-sitter-stack-graphs/src/cli/test.rs
This PR cleans up and clarifies the descriptions of CLI commands and arguments.
=> Clarify CLI command and argument descriptions

tree-sitter-stack-graphs/src/ci.rs, tree-sitter-stack-graphs/src/cli/test.rs
=> Add flag to set max test runtime and limit CI test runner by default

languages/tree-sitter-stack-graphs-java/Cargo.toml, languages/tree-sitter-stack-graphs-typescript/Cargo.toml, lsp-positions/CHANGELOG.md, lsp-positions/Cargo.toml, stack-graphs/CHANGELOG.md, stack-graphs/Cargo.toml, stack-graphs/README.md, tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/README.md, tree-sitter-stack-graphs/npm/package.json
The bumps versions and updates changelogs so we can do a release.
=> New releases

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-javascript/test/computation_flow/function_closure_mutation.js
Implements https://github.com/github/aleph/issues/3080
=> Adds support for VEA Problem 4

tree-sitter-stack-graphs/src/cli/index.rs
As amusing as the concept of a "stank graph" is, I believe "stack graph" was intended here 😄
=> Replace "stank graph" with "stack graph"

.github/workflows/ci.yml, CONTRIBUTING.md, languages/tree-sitter-stack-graphs-java/README.md, languages/tree-sitter-stack-graphs-javascript/README.md, languages/tree-sitter-stack-graphs-typescript/README.md, script/ci-test-init, tree-sitter-stack-graphs/README.md, tree-sitter-stack-graphs/examples/README.md, tree-sitter-stack-graphs/src/cli/init.rs
This PR updates the README of language projects to include a section on basic CLI usage and the commands to run.
Both the generator and the existing language projects are updated to be consistent.
This should give us something to point to for basic "How do I get started" questions.
=> Update README to include some usage guidance

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg
The previous PR was buggy in a way that the test suite didn't catch. :(
Bug for that issue is here: https://github.com/github/stack-graphs/issues/376
=> Class constructor definiens redux

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg
Adds missing syntax types, and also fixes some related bugs
=> Missing function and class syntax types

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-javascript/test/base_syntax.js
=> Object literals containing methods named constructor
