github/stack-graphs

Cargo.toml, src/arena.rs, src/graph.rs, tests/it/can_create_graph.rs, tests/it/graph.rs, tests/it/test_graphs/class_field_through_function_parameter.rs, tests/it/test_graphs/mod.rs, tests/it/test_graphs/sequenced_import_star.rs
This is a slew of types for each of the possible kinds of node that a stack graph can hold, as well as files and edges.
=> Add types to define graph structures

src/arena.rs, src/lib.rs, src/paths.rs, tests/it/arena.rs, tests/it/can_jump_to_definition.rs, tests/it/main.rs, tests/it/paths.rs
We use our new arena-allocated List type to store the symbol and scope stacks efficiently.  The path-finding data is stored in arenas, just like the stack graph structure, but we put those arenas in a separate type.  That will allow us to run multiple path-finding operations in parallel which all consume the same (immutable, already constructed) stack graph.  Maybe that will be useful?
=> Add path-finding algorithm

src/arena.rs, src/graph.rs, src/lib.rs, src/partial.rs, src/paths.rs, tests/it/arena.rs, tests/it/can_find_partial_paths_in_file.rs, tests/it/main.rs
This patch adds the basic partial-path-finding algorithm, along with all of the necessary helper classes.  We're using the same arena-allocated structural sharing pattern for the stack types.  For partial paths, we need both preconditions and postconditions for each stack.
=> Extract partial paths from a file

src/arena.rs, src/cycles.rs, src/lib.rs, src/partial.rs, src/paths.rs, src/utils.rs, tests/it/arena.rs, tests/it/can_create_graph.rs, tests/it/can_find_partial_paths_in_file.rs, tests/it/can_jump_to_definition.rs, tests/it/test_graphs/cyclic_imports_python.rs, tests/it/test_graphs/cyclic_imports_rust.rs, tests/it/test_graphs/mod.rs
This is a simple heuristic that limits the number of paths we process with the same start and end nodes.  Given all of the paths that we encounter with the same start and end nodes, we try to "keep" the ones that are shorter.  Our current threshold is 4 paths.  That said, all of the specifics about this heuristic are subject to change in the future. The only API that we guarantee is that our `CycleDetector` is a black box that says "yes" or "no" to individual paths.
=> Add cycle detection

src/arena.rs, src/lib.rs, src/partial.rs, src/paths.rs, src/stitching.rs, src/utils.rs, tests/it/can_find_node_partial_paths_in_database.rs, tests/it/can_find_root_partial_paths_in_database.rs, tests/it/can_jump_to_definition_with_partial_paths.rs, tests/it/main.rs
This is an implementation of the path stitching algorithm that's divided up into "phases".  At the start of each phase, we process whatever (possibly incomplete) paths are currently in the queue.  As we extend those paths with partial paths, we queue up the newly extended paths to be processed in the _next_ phase.  This phasing approach means that the Database instance doesn't need to be pre-loaded with _all_ of the partial paths that we might ever need to process.  Instead, you're notified of each path in the phase _before_ it will be processed, giving you a chance to add its extensions to the database before allowing the next phase to proceed.
=> Add the path-stitching algorithm

src/graph.rs, tests/it/can_find_node_partial_paths_in_database.rs, tests/it/test_graphs/mod.rs
We can use None for a NodeID's file for these singleton nodes; since handles are non-zero, this is nicely space-efficient.  We just need to choose specific “local ID” values for each of the singleton nodes, and then we can use the existing NodeID type for all nodes in a stack graph.
=> Add node IDs for root and jump-to nodes

src/graph.rs, tests/it/graph.rs
Our new, overly clever interned string storage implementation wasn't handling 0-length strings correctly.  Sprinkle a little bit of unsafe to skip the bounds checks, and we're back in business.
=> Handle empty interned strings correctly

src/graph.rs, tests/it/graph.rs
We don't actually need them!  We'll just make sure to build up a full view of each node before we try to add it to the StackGraph instance.
=> Remove unknown nodes

include/stack-graphs.h, src/c.rs, src/graph.rs, tests/it/c/can_create_graph.rs, tests/it/c/mod.rs, tests/it/c/nodes.rs, tests/it/c/test_graph.rs, tests/it/test_graphs/mod.rs
You provide an array of `sg_node` instances and we add them into the stack graph.  If any of the nodes are invalid, we skip those and return a null handle for them.  Same for edges, although duplicate edges aren't considered an error.
This patch also adds a `TestGraph` helper type, and an implementation of `CreateStackGraph` that calls the A API.  This lets us add a copy of the `can_create_graph` test that exercises the C API instead of the Rust API.
=> Add C bindings for creating nodes and edges

Cargo.toml, include/stack-graphs.h, src/c.rs, src/cycles.rs, src/graph.rs, src/partial.rs, src/paths.rs, tests/it/c/test_graph.rs, tests/it/graph.rs, tests/it/paths.rs, tests/it/test_graphs/mod.rs
Edges can now have precedence values, which can be taken into account when finding or stitching paths.  This is used to model how some definitions can "shadow" others in a source file.
=> Add precedences to edges

include/stack-graphs.h, src/c.rs, src/paths.rs, tests/it/c/can_jump_to_definition.rs, tests/it/c/mod.rs
This function will typically only be useful in test cases, but is a good building block on the way to a C API for the full phased path stitching algorithm.  If you can call this function via the FFI, and validate the results, then everything involving the `StackGraphs` and `Paths` types is working as expected.
=> Add C binding for finding complete paths

include/stack-graphs.h, src/c.rs, tests/it/c/paths.rs
All of our lists and deques use the same value to represent an empty list.  There's no need for separate constants for each one.
=> Use fewer “empty list” constants in C API

include/stack-graphs.h, src/arena.rs, src/c.rs, src/partial.rs, tests/it/c/can_find_partial_paths_in_file.rs, tests/it/c/mod.rs, tests/it/c/partial.rs
This is largely a copy/paste job of the previous PRs to add concrete paths to the C API.  It culminates in another test case that can be invoked purely via the C API, which tests the algorithm that finds partial paths in a file.
=> Add C bindings for partial paths and friends

include/stack-graphs.h, src/c.rs, src/graph.rs, src/partial.rs, src/paths.rs, tests/it/c/nodes.rs, tests/it/c/partial.rs, tests/it/c/paths.rs, tests/it/c/test_graph.rs, tests/it/test_graphs/class_field_through_function_parameter.rs, tests/it/test_graphs/mod.rs
“Push scoped symbol” nodes need to refer to an exported scope node, which will be added to the scope stack that's attached to the symbol that is pushed onto the symbol stack.  Before, you would pass in the handle of the exported scope node.  Now, you pass in its ID.  Both of these are unique identifiers, and so there's no danger of an ambiguous node reference.  This does mean that we need to look up the node's handle as part of the path-finding algorithm, since we are still storing node handles in our scope stack representations.
The reason for this change is that before this patch, you had to add nodes to a stack graph in separate passes: first you would add your exported scope nodes, and only then would you add your pushed scope symbol nodes.  You had to use this ordering so that you'd …
=> Refer to exported scopes by ID, not handle

include/stack-graphs.h, src/c.rs, tests/it/c/files.rs, tests/it/c/nodes.rs, tests/it/c/partial.rs, tests/it/c/paths.rs, tests/it/c/symbols.rs, tests/it/c/test_graph.rs
Symbols and files both consist only of a single string.  Before, the C API functions for bulk-loading symbols and files expected you to pass in an array of arrays of string content.  This patch updates the functions to have you pass in a single `const char*`, containing the content of everything you want to add _concatenated together_. Consumers will already likely be building up the string content dynamically, and so it's not harder to build that up into a single string buffer instead of into an array of string pointers.  And the result should both require fewer allocations in all languages, and should play more nicely with Cgo in particular, which prohibits Go pointers within Go pointers for any data that you pass into a C call.
=> Use “collapsed” strings in C API 

include/stack-graphs.h, src/c.rs, src/graph.rs, tests/it/c/nodes.rs, tests/it/c/partial.rs, tests/it/c/paths.rs, tests/it/c/test_graph.rs
The C API's function for adding nodes to a stack graph is now a “get or create” function.  If there's already a node in the stack graph with the same ID, we now return the handle of the existing node, instead of a null handle.  We've renamed the function to make it explicitly clear that there's a change of behavior.
=> Get or create nodes in C API

include/stack-graphs.h, src/c.rs, src/stitching.rs, tests/it/c/can_jump_to_definition_with_partial_paths.rs
The C API function for adding partial paths to a database now returns the handles of those partial paths, and there's a new accessor function that gives access to the underlying arena.  This will be helpful in test cases that add partial path content manually, so that you can verify that they were added as expected.
=> Return partial path handles in C API

.github/workflows/ci.yml, Cargo.toml, src/arena.rs, src/graph.rs, src/partial.rs, src/paths.rs, tests/it/c/files.rs, tests/it/c/nodes.rs, tests/it/c/partial.rs, tests/it/c/paths.rs, tests/it/c/symbols.rs, tests/it/can_find_root_partial_paths_in_database.rs, tests/it/paths.rs
Our C API already includes comments describing how null values are stored for several types.  This patch adds test cases to verify that that's actually how we're storing them in memory.  In several cases (mostly involving attached scope lists), we weren't, because the Rust compiler was choosing a different field deep down inside the struct to sneak the None value into.  (In particular, anything with a `Deque` was using the value 2 for the deque's `direction` field, instead of the value 0 for its `list` field.)
Fixing the test cases required a new [`controlled-option` crate](https://docs.rs/controlled-option/*/), which uses a new `Niche` trait to take control over which "niche" value is used to represent a None value.  This lets us explicitly say, for instance, that null deques should use …
=> Take control of C representation of None values

src/arena.rs, src/c.rs, src/paths.rs, src/stitching.rs, tests/it/c/can_jump_to_definition_with_partial_paths.rs
The forward path stitcher returns a list of paths that have been encountered in the most recent phase.  In the C wrapper API, we need to ensure that the content of each paths' edge list is available in either direction, so that the C caller can iterate through them in either direction.
=> Ensure edge lists are available in both directions

.github/workflows/ci.yml, Cargo.toml, src/debugging.rs, src/lib.rs, src/stitching.rs, tests/it/c/can_jump_to_definition_with_partial_paths.rs, tests/it/can_find_node_partial_paths_in_database.rs, tests/it/can_find_root_partial_paths_in_database.rs
We already had some nice debugging messages in one of the jump-to-def test cases.  This patch moves them into the library proper, gated behind a new `copious-debugging` feature flag.
=> Add ‘copious-debugging’ feature flag

src/partial.rs, tests/it/main.rs, tests/it/partial.rs
This is the partial stack equivalent of checking whether a scope stack satisfies a partial scope stack.  In this case, you're comparing two partial scope stacks, determining whether there is _any_ set of scope stacks that satisfies both, and returning the “unified” partial scope stack that represents that set.  While doing so, we have to take into account any existing variable assignments, and possibly create new ones. Fun!
=> Add function for unifying partial scope stacks

include/stack-graphs.h, src/c.rs, src/partial.rs, tests/it/c/can_find_partial_paths_in_file.rs, tests/it/c/partial.rs, tests/it/can_find_node_partial_paths_in_database.rs, tests/it/can_find_partial_paths_in_file.rs, tests/it/can_find_root_partial_paths_in_database.rs
We had several comments that talked about how we used an “implicit” symbol stack variable in our partial symbol stacks.  As we move towards a path-stitching algorithm that operates entirely on partial stacks, it's more important to have consistency between the implementations of the two stacks.  So this patch adds in symbol stack variables as a first-class type in the data model.
=> Add explicit symbol stack variables 

src/partial.rs, src/paths.rs, tests/it/c/can_find_partial_paths_in_file.rs, tests/it/can_find_node_partial_paths_in_database.rs, tests/it/can_find_partial_paths_in_file.rs, tests/it/partial.rs, tests/it/paths.rs
This is very much like the function that we recently addded for unifying partial scope stacks.  There is some extra complexity from having to deal with attached scope stacks.
=> Add function for unifying partial symbol stacks 

stack-graphs/include/stack-graphs.h, stack-graphs/src/c.rs, stack-graphs/src/graph.rs, stack-graphs/tests/it/c/can_find_partial_paths_in_file.rs, stack-graphs/tests/it/c/files.rs, stack-graphs/tests/it/c/nodes.rs, stack-graphs/tests/it/c/partial.rs, stack-graphs/tests/it/c/paths.rs, stack-graphs/tests/it/c/strings.rs, stack-graphs/tests/it/c/symbols.rs, stack-graphs/tests/it/c/test_graph.rs, stack-graphs/tests/it/graph.rs
This lets you add arbitrary string content to a stack graph, which will be interned and deduplicated just like we're already doing for symbols and filenames.  We're going to use this soon for some supplemental information about stack graph nodes that are associated with a range of content in a source file.
=> Add `InternedStrings`

.github/workflows/ci.yml, Cargo.toml, lsp-positions/Cargo.toml, lsp-positions/README.md, lsp-positions/src/lib.rs, lsp-positions/tests/it/main.rs, stack-graphs/Cargo.toml, stack-graphs/include/stack-graphs.h, stack-graphs/src/arena.rs, stack-graphs/src/c.rs, stack-graphs/src/graph.rs, stack-graphs/tests/it/c/nodes.rs
This moves over some of our existing logic for dealing with LSP-compatible character positions and lets you start tracking this for stack graph nodes.  All of the position information is stored in a supplemental arena, and is completely optional.
(LSP indexes characters as their [location within the UTF-16 encoding of the string](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocuments), even if the string content is stored in UTF-8.  That means we need to track UTF-8 offsets, so that we can efficiently index into the Rust strings, but also track UTF-16 if we ever want to provide an LSP view of this data.)
=> Track lots of position information

stack-graphs/src/partial.rs
We already had a constructor that takes in a `u32`, but that can fail, since we have to verify that you don't pass in a 0.  If you already have a `NonZeroU32`, we can skip that check and use these new `From` instances.
=> Add additional `From` instances for stack variables

stack-graphs/Cargo.toml, stack-graphs/include/stack-graphs.h, stack-graphs/src/arena.rs, stack-graphs/src/c.rs, stack-graphs/src/graph.rs, stack-graphs/src/partial.rs, stack-graphs/src/stitching.rs, stack-graphs/tests/it/c/can_find_local_nodes.rs, stack-graphs/tests/it/c/mod.rs, stack-graphs/tests/it/can_find_local_nodes.rs, stack-graphs/tests/it/graph.rs, stack-graphs/tests/it/main.rs, stack-graphs/tests/it/test_graphs/mod.rs
A node is local if it cannot possibly participate in a name binding that leaves its file.  In a stack graph, that means that there is no sequence of partial paths that connects the node to the root node.
We have two methods for “setting” the set of local nodes.  The first is meant to be called at index time, and actually analyzes the partial paths in the database to determine which nodes are local.  The second is meant to be called at query time, where you've stored the locality information in your storage layer, and just need to load that back into our internal view of the stack graph.
=> Determine which nodes in a file are “local”

lsp-positions/Cargo.toml, lsp-positions/src/lib.rs, lsp-positions/tests/it/main.rs, stack-graphs/include/stack-graphs.h, stack-graphs/src/c.rs
This PR adds support for computing grapheme positions, next to the UTF-8 and UTF-16 positions already tracked. Graphemes are useful for reasoning about corresponding positions between lines, and for use as column positions reported to users.
Because not all users may need both UTF-16 and graphemes, both features are now behind a feature (`utf16` and `graphemes` repsectively), allowing lean use.
**Limitations**
Graphemes work for visual alignment purposes as long as all characters a the same width. Even with fixed-width fonts this is not always the case, e.g. for East Asian characters or Emojis.
=> Add support for grapheme positions

stack-graphs/include/stack-graphs.h, stack-graphs/src/c.rs, stack-graphs/src/stitching.rs, stack-graphs/tests/it/c/can_jump_to_definition_with_phased_partial_path_stitching.rs, stack-graphs/tests/it/c/can_jump_to_definition_with_phased_path_stitching.rs
In our phased path stitching algorithms, you can now bound the total amount of work that can be performed in each phase.
The mechanics of using the stitching classes are exactly the same — check which paths were newly discovered in the previous phase, and load any possible extensions of them into the database before starting the next phase.
The limit is configurable, and defaults to the previous behavior of no additional bound.  (There is always _some_ limit on the amount of work performed, since we only process extensions of paths found in previous phases.)
=> Bound the amount of work performed in each phase

.github/workflows/ci.yml, stack-graphs/CHANGELOG.md, stack-graphs/include/stack-graphs.h, stack-graphs/src/c.rs, stack-graphs/src/stitching.rs, stack-graphs/tests/it/c/can_find_qualified_definitions_with_phased_partial_path_stitching.rs, stack-graphs/tests/it/c/mod.rs
You can now instantiate the forward partial path stitcher with an explicit list of initial partial paths.  From there, the phased algorithm proceeds exactly as before.  This lets us implement “find qualified definitions”, where we look for any definition that is reachable from a particular fully qualified name (expressed as a symbol stack).
=> Allow stitching from arbitrary partial paths

stack-graphs/include/stack-graphs.h, stack-graphs/src/c.rs, stack-graphs/src/graph.rs, stack-graphs/src/partial.rs, stack-graphs/tests/it/c/nodes.rs, stack-graphs/tests/it/c/partial.rs, stack-graphs/tests/it/c/paths.rs, stack-graphs/tests/it/c/test_graph.rs, stack-graphs/tests/it/partial.rs, stack-graphs/tests/it/test_graphs/mod.rs
Since internal and external scopes do not really differ in behavior and the difference is only used for selection, I propose to unify them and use a flag to indicate exported scopes, in the same way as we do for references and definitions.
* Replaces `InternalScope` and `ExternalScope` with a single `Scope`, and use an `is_exported` flag to indicate if the scope is exported.
* The `is_clickable` field in the C API is renamed to `is_endpoint`, which represents `is_exported`, `is_reference`, and `is_definition`.
=> Unify internal and exported scopes

stack-graphs/src/json.rs, stack-graphs/tests/it/json.rs
I should have reviewed the test carefully instead of merging it quickly 🙈. There were some issues, that are addressed in this PR.
- Fix swap names for `push_symbol` and `push_scoped_symbol`
- Use correct value for `scope` in `push_scoped_symbol`
- Use node ids in edges and paths, instead of inlining the node itself.
- Use `scopes` instead of `scoped_stack` to stay close to Rust API.
- Pretty print expected JSON with key sorting so its easier to keep stable in the future
=> Fixes in JSON serialization

stack-graphs/src/assert.rs, tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/README.md, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/loader.rs, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/main.rs, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/test.rs, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/loader.rs, tree-sitter-stack-graphs/src/test.rs, tree-sitter-stack-graphs/tests/it/main.rs, tree-sitter-stack-graphs/tests/it/test.rs
This adds language loading and test parsing & running to the library, and a test command to the CLI.
Example output of a test run:
```
✓ ../tree-sitter-code-nav/test/typescript/statements/import-as-namespace.ts: 3/3 assertions
✓ ../tree-sitter-code-nav/test/typescript/statements/import-indirectly-exported-variable.ts: 4/4 assertions
✓ ../tree-sitter-code-nav/test/typescript/statements/let-without-value.ts: 3/3 assertions
✓ ../tree-sitter-code-nav/test/typescript/statements/import-from-subdirectory.ts: 3/3 assertions
✗ ../tree-sitter-code-nav/test/typescript/statements/shadowing.ts: 0/6 assertions
../tree-sitter-code-nav/test/typescript/statements/shadowing.ts:6:8: definition(s) for reference(s) ‘T’ found unexpected ‘T’ on lines(s) 1 …
```
=> Implement CLI to use stack graphs with tree-sitter

tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/test.rs, tree-sitter-stack-graphs/src/functions.rs, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/loader.rs, tree-sitter-stack-graphs/tests/it/edges.rs, tree-sitter-stack-graphs/tests/it/nodes.rs, tree-sitter-stack-graphs/tests/it/test.rs
This PR improves the path functions that are provided.
The current functions are:
- `normalize`, which normalizes a path be removing `.` and `..` components
- `resolve`, which takes two paths and resolves the second relative to _the parent of_ the first.
The `resolve` function does too many things, and doesn't give the use enough control. I have split it up and created now the following functions (following what several API's do for paths): `path-dir`, `path-filext`, `path-filename`, `path-filestem`, `path-join`, `path-normalize` (as it was), and `path-split`.
=> Add path functions

tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/loader.rs, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/main.rs, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/test.rs, tree-sitter-stack-graphs/src/functions.rs
Currently any file output produced by the CLI is put next to the input file it relates to. This PR adds optional arguments to the `--save-*` flags to specify the filename. Placeholders can be used that are substituted based on the input path.
The default changed to saving the file in the current directory, using the same name as the test file, but excluding directories. For example, `%n.html` for visualization.
One notable change is that `--save-*` take their argument with equals signs instead of using a separate argument. So, `--save-graph=%n.html` instead of `--save-graph %n.html`. This is to prevent accidental overwriting of user files when a user issues a command such as `tree-sitter-stack-graphs test --save-graph first.py second.py` where `first.py` would unintentionally be …
=> Add CLI options to control output files

stack-graphs/tests/it/c/can_find_qualified_definitions_with_phased_partial_path_stitching.rs
Turns out we don't need this step — the initial partial paths show up as the “previous phase” and so we'll load in their extensions in the while loop below.
=> Remove extra work from find qualified defs test

tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/test.rs, tree-sitter-stack-graphs/src/test.rs, tree-sitter-stack-graphs/tests/it/test.rs
Test files that do not contain `--- path: XYZ ---` headers consist of a single test fragment.
Currently we use the source as the path of this fragment.
This may not always be desriable, e.g. we may want to use a path relative to a test root instead.
This PR adds an argument to `Test::from_source` to pass the path to be used for this single fragment.
=> Add argument to control the default test fragment path

stack-graphs/CHANGELOG.md, stack-graphs/src/graph.rs, stack-graphs/tests/it/graph.rs, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/test.rs, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/loader.rs, tree-sitter-stack-graphs/src/test.rs
This PR adds support for loading builtins automatically from the grammar repository.
Builtins are loaded from `GRAMMAR_REPO/queries/builtins.EXT` for any of the grammar extensions.
Builtins are expected to be source files in the target language, which will be parsed and processed using the language's TSG file to get the corresponding stack graph.
Builtins are added as a field on stack graph languages.
A method `StackGraph::add_graph` is added to copy the content of one graph into another.
=> Support builtins

stack-graphs/src/json.rs, stack-graphs/src/visualization.rs, stack-graphs/tests/it/json.rs, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/test.rs
With the support for builtins, the JSON and HTML output contain all the builtin information as well. This makes the visualization unusable and prohibits debugging anything.
This PR adds support for filtering the output to the API, and implements filtering for the CLI output so that only graph & paths coming from the test source itself are included.
=> Support filtering JSON/HTML output

tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/README.md
- Bump tree-sitter-graph dependency to 0.5.0
- Bump tree-sitter-stack-graphs to 0.1.0 and update README
=> First tree-sitter-stack-graphs release (0.1.0)

stack-graphs/CHANGELOG.md, stack-graphs/src/stitching.rs, stack-graphs/tests/it/partial.rs
A divergent partial path is one that starts at the root node and has an empty symbol stack precondition.  That empty precondition means that it can be concatenated to _any_ path that currently ends at the root node — including the result of that concatenation!  That gives us a divergence, since we can continually prepend the path's postcondition to the current symbol stack, forever.
This patch adds a check that ensures that we never add this kind of partial path to a `Database` instance.  (Without this check, we would end up allocating an unusably large amount of memory, since we're currently representing empty lists with a `u32::max` arena handle!)
=> Don't add divergent partial paths to database

stack-graphs/include/stack-graphs.h, stack-graphs/src/c.rs, stack-graphs/src/graph.rs, stack-graphs/tests/it/c/nodes.rs, stack-graphs/tests/it/test_graphs/simple.rs
This PR adds definiens nodes for the bodies of defined functions and so forth.
This is will let us start tracking hierarchical TOCs and function calls for richer vulnerability flagging.
=> Adds fields for definiens

stack-graphs/include/stack-graphs.h, stack-graphs/src/c.rs, stack-graphs/src/partial.rs, stack-graphs/src/stitching.rs
This adds methods and C API functions that allow changing the deque direction for paths in the path database.
Paths have internal components that can be represented forwards or backwards in the arena.
When a deque is reversed so that it is backwards, a pointer is stored to the reversed (i.e., forward) chain of cells.
However, the reverse pointer is not preserved when pushing to a backwards list.
It was not easy for consumers of the C API to get the forwards list from such a backwards list.
This PR adds functions to the C API that ensure that all paths in the database have either a forwards direction, or both directions available.
=> Add methods and C API function to change deque direction of paths in the database

tree-sitter-stack-graphs/src/lib.rs
Previously, under the  "Referring to the singleton nodes" section, the documentation says to create an edge from ROOT_NODE to a defition node with a tsg_source you must write `edge (ROOT_NODE -> def)`, however, this throws a `ParseError` because *as I understand* the parenthesis are used to reference already created nodes/edges. A simple fix in the documentation from `edge (ROOT_NODE -> def)` to `edge ROOT_NODE -> def` should help out someone new who might get a slight headache trying to figure out why the code in the docs isn't working.
=> Fix Edge Definition in Docs

stack-graphs/CHANGELOG.md, stack-graphs/src/c.rs, stack-graphs/src/partial.rs, stack-graphs/tests/it/can_find_local_nodes.rs, stack-graphs/tests/it/can_find_node_partial_paths_in_database.rs, stack-graphs/tests/it/can_find_partial_paths_in_file.rs, stack-graphs/tests/it/can_find_root_partial_paths_in_database.rs, stack-graphs/tests/it/can_jump_to_definition_with_forward_partial_path_stitching.rs, stack-graphs/tests/it/can_jump_to_definition_with_forward_path_stitching.rs
Partial paths are now computed from references only, instead of from any push node. This aligns with the existing behavior for scopes, where only exported scopes are used as start nodes.
=> Only compute partial paths from references

tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/test.rs, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/loader.rs, tree-sitter-stack-graphs/tests/it/builder.rs, tree-sitter-stack-graphs/tests/it/edges.rs, tree-sitter-stack-graphs/tests/it/main.rs, tree-sitter-stack-graphs/tests/it/nodes.rs, tree-sitter-stack-graphs/tests/it/test.rs
It can be useful to be able to programatically create nodes and edges in the stack graph, and pass those to tree-sitter-stack-graph as globals, so they can be used in a TSG.
At the moment, this is not possible at all. If preexisting nodes even exist, loading the result from TSG into the stack graph fails.
This PR adds functionality to prevent crashes and support using references to existing nodes as global variables.
See reported issue in #104.
=> Support preexisting nodes

stack-graphs/CHANGELOG.md, stack-graphs/Cargo.toml, tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/Cargo.toml
Minor releases so they are available for use in tree-sitter-code-nav.
=> Release stack-graphs 0.10.1 and tree-sitter-stack-graphs 0.3.1

tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/loader.rs, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/test.rs, tree-sitter-stack-graphs/src/loader.rs, tree-sitter-stack-graphs/src/test.rs, tree-sitter-stack-graphs/tests/it/test.rs
TSG files can declare global variables hey expect to be set in the environment by the
caller. Tree-sitter-stack-graphs sets a few of these by default, such as `ROOT_NODE` and
`FILE_PATH`. There was no way of specifying other global variables, which made TSG files which
require more variables than those untestable.
This PR adds support for setting global variables in two situations:
1. In tests files, global variables can be set in comments. For example:
pass
2. Global variables for the builtins loaded from the grammar repository can be specified in an
optional configuration file `queries/builtins.cfg` alongside the builtins file itself. For
example:
[globals]
PKG=std
=> Add support fer globals in tests and builtins

tree-sitter-stack-graphs/examples/.gitignore, tree-sitter-stack-graphs/examples/README.md, tree-sitter-stack-graphs/examples/modules/stack-graphs.tsg, tree-sitter-stack-graphs/examples/modules/tests/import-all-definitions-from-nested-module.py, tree-sitter-stack-graphs/examples/modules/tests/import-all-definitions-from-toplevel-module.py, tree-sitter-stack-graphs/examples/modules/tests/import-single-definition-from-nested-module.py, tree-sitter-stack-graphs/examples/modules/tests/import-single-definition-from-toplevel-module.py, tree-sitter-stack-graphs/examples/run
- Add modules and imports examples. Fixes #118.
- Add `-V` flag to run script to easily generate visualizations.
=> Add modules example

.github/workflows/publish-lsp-positions-crate.yml, .github/workflows/publish-stack-graphs-crate.yml, .github/workflows/publish-tree-sitter-stack-graphs-crate.yml
This adds actions that publish the crate when a `CRATE_NAME-v*` tag is pushed.
Docs for the publish action: https://github.com/marketplace/actions/publish-crates
It would be nice to verify that the tag matches the version of the crate, but I couldn't quickly figure out a way to do that.
=> Add actions to publish crates on tags push

tree-sitter-stack-graphs/examples/README.md
The directory was named nested-scope,
not nested-scoping.
=> tree-sitter/examples: Fix link to "Nested scoping"

tree-sitter-stack-graphs/examples/README.md, tree-sitter-stack-graphs/examples/parse, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/main.rs, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/parse.rs, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/test.rs, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/util.rs, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/loader.rs
Being able to view the parse tree is essential when developing TSG
files. Currently this requires setting up Tree-sitter, ensuring it is
configured correctly. This PR adds a convenient `tree-sitter-stack-graphs
parse` command, that prints a parse tree without having to do all
that. It accepts the same arguments and uses the same loading mechansim
for grammars as the `test` command.
A new `tree-sitter-stack-graphs/examples/parse` script allows for easy parsing of example files.
=> Add command to show parse tree

tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/loader.rs, tree-sitter-stack-graphs/src/loader.rs
This PR changes the stack graph langauge loader to use search paths for loading TSG and builtins files.
The current setup would not support custom builtins locations, and the need to implement a custom reader (with TSG parsing) was a bit cumbersome for users.  Since the loader is already specific to the scenario where grammars are loaded from the filesystem, it seems the flexibility of the reader is unnecessary.  The new setup using search paths is closer to many loading mechanisms and easier for users.
=> Support search paths in loader

tree-sitter-stack-graphs/npm/.gitignore, tree-sitter-stack-graphs/npm/cli.js, tree-sitter-stack-graphs/npm/install.js, tree-sitter-stack-graphs/npm/package.json
Most Tree-sitter projects are configured using NPM. This PR publishes the tree-sitter-stack-graphs CLI as an NPM package to make it easier to integrate into grammar projects.
Once published, projects should be able to declare a `devDependency` on `tree-sitter-stack-graphs` and run the CLI using `npx tree-sitter-stack-graphs`.
=> Add NPM package

tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/README.md, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/init.rs, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/main.rs
This PR tries to make it easier to get started with stack graphs. It introduces an `init` command that initializes a new project for an NPM distributed Tree-sitter grammar.
Depends on #132. _Note that the generated projects will not work until a new version of `tree-sitter-stack-graphs` is released, in case you'd try it locally from the development branch!_
The command will ask for various settings from the console:
```
$ tree-sitter-stack-graphs init java-stack-graphs
Creating project directory: java-stack-graphs
Give the name of the programming language the stack graphs definitions in this
project will target. This name will appear in the project description and comments.
Language name: Java
Give an identifier for Java. This identifier will be used for the suggested project
name and …
```
=> Add command to initialize new project

tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/parse.rs
Positions are always displayed to users as one-based. The parse code did not do that. This PR changes that.
=> Use one-based positions in user facing output

.github/workflows/ci.yml, .github/workflows/publish-tree-sitter-stack-graphs-npm.yml, tree-sitter-stack-graphs/npm/README.md, tree-sitter-stack-graphs/npm/package-lock.json
This adds some workflows and docs for the NPM package:
- A job to CI to test a successful package install 
- A workflow that publishes the package to the NPM Registry whenever a version tag is pushed.
- A brief README for the NPM package, so people are not presented an empty page when visiting the package on NPM.
=> Automate NPM testing & publishing

.zenodo.json
Once the first release shows up and we have a DOI, I'll also add (in a separate PR) a `CITATION.cff` file that GitHub will render.
=> Add Zenodo citation file

.github/workflows/publish-lsp-positions.yml, .github/workflows/publish-stack-graphs.yml, .github/workflows/publish-tree-sitter-stack-graphs.yml
As it turns out, the action used for releasing the crate has some issues.
- It does not work well with crates that have non-crates.io dependencies. In our case, we use relative path dependencies. This crashes the action run.
- The dry run doesn't do a `cargo publish --dry-run`, as I expected, but only an action dry run, skipping cargo completely.
In light of this, and the fact that it is not doing much more than invoking cargo anyway, this PR relaces the action with direct cargo invocations. It also runs the tests once more before publishing, as an extra safe guard, since there is no guarantee that the tag has gone through PR & CI.
=> Fix publishing workflows

tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/npm/package.json
Move tree-sitter-stack-graphs to version 0.4.1. This will incorporate some fixes and hopefully the CI release process will cooperate this time.
=> Bump tree-sitter-stack-graphs to version 0.4.1

tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/main.rs, tree-sitter-stack-graphs/src/cli.rs, tree-sitter-stack-graphs/src/cli/init.rs, tree-sitter-stack-graphs/src/cli/load.rs, tree-sitter-stack-graphs/src/cli/parse.rs, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/cli/util.rs, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/loader.rs, tree-sitter-stack-graphs/src/test.rs, tree-sitter-stack-graphs/tests/it/loader.rs, tree-sitter-stack-graphs/tests/it/main.rs
This PR moves most of the CLI logic to the library (though still behind the `cli` feature!). This makes it possible to (a) create specialized CLIs whith included languages, and (b) run them programmatically from tests.
- ▶️ #146
- #140 
- #142
=> Expose cli logic through lib

stack-graphs/Cargo.toml, stack-graphs/src/arena.rs
Our bitvec dependency depended on another library version that was yanked from cargo. This updates bitvec to the latest version so that we can build again.
=> Bump bitvec to 1.0

languages/tree-sitter-stack-graphs-typescript/Cargo.toml, languages/tree-sitter-stack-graphs-typescript/rust/bin.rs, languages/tree-sitter-stack-graphs-typescript/rust/lib.rs, languages/tree-sitter-stack-graphs-typescript/rust/test.rs, languages/tree-sitter-stack-graphs-typescript/src/stack-graphs.tsg, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/loader.rs, tree-sitter-stack-graphs/tests/it/loader.rs
A `Loader` would return instances of `StackGraphLanguage`, given a language name or file name. This PR changes the loader to return `LanguageConfiguration` instances instead, which exposes more information about the language to the user, instead of hiding it.
- This makes it easier to check, after loading a language for a file, to check if another file belongs to the same language or not.
- This will make it easier (in a follow-on PR) to allow different stank graph construction methods for different files.
- This allows us to remove the builtins `StackGraph` instance from a `StackGraphLanguage`. This was a code smell, since the SGL and the builtins are independent, and used in different steps in the processing.
Previously, a `LanguageConfiguration` would hold the _sources_ of TSG and …
=> Reorganize loader

languages/tree-sitter-stack-graphs-typescript/rust/lib.rs, languages/tree-sitter-stack-graphs-typescript/rust/tsconfig.rs, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/loader.rs, tree-sitter-stack-graphs/src/test.rs, tree-sitter-stack-graphs/tests/it/loader.rs
This PR adds support for custom file analyzers for specific file names, for example a file analyzer that generates stack graph for `tsconfig.json`. The idea is that this mechanism will be used for project or package configuration files.
These configuration files require more context than regular source files. For example, `tsconfig` needs all source paths in a project to infer the project's root directory. At the moment, all project paths are provided as a parameter, but we may need more information in the future. I wonder if that set is finite, if it is small or large, and whether parameters are the right way to provide this info, or something more similar to the global variables passed to TSG (that is, more open, but less typed).
- https://github.com/github/stack-graphs/pull/153
- …
=> Add file analyzers

stack-graphs/src/visualization/visualization.css, stack-graphs/src/visualization/visualization.js
The visualization indicates whether nodes are push or pop using (a) color, and (b) an up or down arrow before the symbol:
I always forget which color is which, and the arrows are quite small if zoomed out a bit. This PR would make the node shapes more obviously pop/push by incorporating the arrow as part of the node, instead of the symbol:
I think this makes it easier to see which nodes are which. Happy to hear opinions. Bikeshedding re colors etc allowed in this PR.
=> Use node shape instead of symbol to indicate push and pop nodes

languages/tree-sitter-stack-graphs-typescript/Cargo.toml, stack-graphs/CHANGELOG.md, stack-graphs/Cargo.toml, tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/Cargo.toml
This bumps versions to enable a new release of tree-sitter-stack-graphs. The latest v0.4.1 release broke when the `bitvec` dependency yanked some versions from crates.io. This release should ensure installing via `cargo install` works again.
Addresses #159.
=> Release stack-graphs v0.10.2 and tree-sitter-stack-graphs v0.5.0

languages/tree-sitter-stack-graphs-typescript/Cargo.toml, languages/tree-sitter-stack-graphs-typescript/rust/lib.rs, languages/tree-sitter-stack-graphs-typescript/rust/npm_package.rs, languages/tree-sitter-stack-graphs-typescript/rust/tsconfig.rs, languages/tree-sitter-stack-graphs-typescript/rust/util.rs, languages/tree-sitter-stack-graphs-typescript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-typescript/test/projects/package-with-baseurl.ts, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/test.rs
This adds a simple `package.json` analyzer that exposes the package in the global scope, and resolves imports into the package to the correct modules in the inferred root directory.
This is a very simple approach, but it shows that the encoding for modules and packages is refined enough to deal with package definitions based on `package.json`.
It is limited, because package visibility cannot be controlled. In particular, if the stack graphs of multiple repositories are combined, and packages with the same name are defined multiple times, this approach cannot ensure one particular one is used. Other approaches are possible, for example, keeping the package definitions local to a project, and resolving them in specific other projects. (Assuming project names are globally unique.) The good …
=> Analyze package.json

languages/tree-sitter-stack-graphs-typescript/rust/npm_package.rs, languages/tree-sitter-stack-graphs-typescript/rust/tsconfig.rs, languages/tree-sitter-stack-graphs-typescript/rust/util.rs
This cleans up the code for `tsconfig.json` and `package.json` and ensures all nodes get a debug name attached to it. Previously, for module names, only the final component had debug info attached to it.
=> Cleanup code and ensure all components of module names have a debug name attached

languages/tree-sitter-stack-graphs-typescript/rust/bin.rs, languages/tree-sitter-stack-graphs-typescript/rust/test.rs, tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/main.rs, tree-sitter-stack-graphs/src/ci.rs, tree-sitter-stack-graphs/src/cli.rs, tree-sitter-stack-graphs/src/lib.rs
Instead of providing a fully derived CLI type, the subcommands are now exposed, while deriving the CLI type is left to the user.
This makes sure that the name and version reported by the version command are ones from the user crate, and not from this crate.
The effect can be seen in the version output of `tree-sitter-stack-graphs-typescript`. Before:
```
$ cargo run -- --version
tree-sitter-stack-graphs 0.5.1
```
And after:
```
$ cargo run -- --version
tree-sitter-stack-graphs-typescript 0.1.0
```
=> Reorganize CLI code

languages/tree-sitter-stack-graphs-typescript/Cargo.toml, tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/README.md, tree-sitter-stack-graphs/npm/package.json
Release tree-sitter-stack-graphs v0.6.0. This fixes a small issue which is a blocker for releasing `tree-sitter-stack-graphs-typescript`.
=> Release tree-sitter-stack-graphs v0.6.0

languages/tree-sitter-stack-graphs-typescript/rust/npm_package.rs, languages/tree-sitter-stack-graphs-typescript/rust/tsconfig.rs, languages/tree-sitter-stack-graphs-typescript/src/builtins.cfg, languages/tree-sitter-stack-graphs-typescript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-typescript/test/modules/import-from-ambient-module-declaration.ts
This PR removes almost all references to `ROOT_NODE` and ensures things are properly scoped within the project.
This ensures we have as much control as possible over where information is visible.
The builtins, as a result, or not a global thing anymore, but something that is explicitly imported into every file.
=> [TypeScript] Scope everything within projects

tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/src/cli.rs, tree-sitter-stack-graphs/src/cli/analyze.rs, tree-sitter-stack-graphs/src/cli/parse.rs, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/cli/util.rs, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/loader.rs, tree-sitter-stack-graphs/tests/it/loader.rs
This adds a rudimentary `analyze` command to the CLI. For now it takes a path, builds stack graphs for the sources, and computes partial files per file's stack graph.
- A `--max-file-time` flag sets a timeout on analysis for a single file. Default is unlimited.
- A `--verbose/-v` flag prints all files as they are being processed. Without it, only files with problems are printed.
- Console printing is made debug friendly by printing the file names _before_ analysis starts, so if excessive runtime of memory usage occurs, it is immediately clear which file is the cause.
In the future, it might store the graphs and/or paths in a database which can then be queried, etc.
Additionally, the language detection code, which accepted a `&str` parameter for the file content, has been changed to take a …
=> Add `analyze` command

tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/test.rs
This does some cleanup for the `test` command:
- Change `--show-ignored` to `--show-skipped`, which only displays explicitly skipped tests (with a `.skip` extension), instead of just any file that happens to be in the test folder (such as generated `.html`).
- Change console output to be debugging friendly. Test names are displayed before the test is run, making debugging excessive runtime and memory usage easier. It is now similar to the output of `analyze`.
- Fix a panic when an assertion refers to a line beyond the end of a file.
=> Cleanup `test` command

stack-graphs/src/partial.rs, stack-graphs/src/paths.rs, stack-graphs/src/stitching.rs, stack-graphs/tests/it/c/can_find_local_nodes.rs, stack-graphs/tests/it/c/can_find_partial_paths_in_file.rs, stack-graphs/tests/it/c/can_jump_to_definition_with_phased_partial_path_stitching.rs, stack-graphs/tests/it/can_find_local_nodes.rs, stack-graphs/tests/it/can_find_node_partial_paths_in_database.rs, stack-graphs/tests/it/can_find_partial_paths_in_file.rs, stack-graphs/tests/it/can_jump_to_definition_with_forward_partial_path_stitching.rs, stack-graphs/tests/it/partial.rs
Partial path code is incomplete or broken in several ways:
1. Lifting nodes to partial paths was incorrect for several node types
2. Path concatenation is incorrect for certain connecting nodes (the node shared between left & right)
This PR fixes these and adds test as well.
Re 1. I've addressed this be refactoring the existing code for `PartialPath::append` so that the logic to apply a node to a set of pre- and postcondition stacks can be used independently of a partial path as well. The `PartialPath::from_node` now creates some default stack sand simply uses that logic. This also reduces some duplication that existed between `from_node` and `append`.
Re 2. This was a fun one, that surfaced when I experimented with different partial path finding strategies. I noticed that stitching …
=> Partial path improvements

languages/tree-sitter-stack-graphs-typescript/README.md, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/README.md, tree-sitter-stack-graphs/src/cli/init.rs, tree-sitter-stack-graphs/src/cli/init/license.rs, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/loader.rs, tree-sitter-stack-graphs/src/test.rs, tree-sitter-stack-graphs/tests/it/loader.rs, tree-sitter-stack-graphs/tests/it/test.rs
The `init` command generates NPM based projects. Recently we have switched
over to using Cargo and Rust instead. This PR changes the `init` command
to generate Cargo projects instead of NPM projects.
I have chosen not to keep the NPM project generation around. The Cargo
setup is much cleaner. The NPM package will remain supported for the
time being, so it would be possible for NPM based projects to integrate
stack graphs, but they'll have to set it up manually.
The console interaction was also improved a little. Input values can now
be revised instead of only having the option to generate or cancel at the
end of the input cycle.
Fixes #175.
https://user-images.githubusercontent.com/999073/216321666-6557dbf2-d979-4d7e-814b-9570d188ed31.mov
=> Generate Cargo projects with `init`

stack-graphs/Cargo.toml, stack-graphs/src/arena.rs, stack-graphs/src/assert.rs, stack-graphs/src/c.rs, stack-graphs/src/graph.rs, stack-graphs/src/json.rs, stack-graphs/src/partial.rs, stack-graphs/src/paths.rs, stack-graphs/src/stitching.rs, stack-graphs/src/visualization.rs, stack-graphs/tests/it/c/can_find_partial_paths_in_file.rs, stack-graphs/tests/it/can_find_local_nodes.rs, stack-graphs/tests/it/can_find_node_partial_paths_in_database.rs, stack-graphs/tests/it/can_find_partial_paths_in_file.rs, stack-graphs/tests/it/can_find_root_partial_paths_in_database.rs, stack-graphs/tests/it/can_jump_to_definition_with_forward_partial_path_stitching.rs, stack-graphs/tests/it/can_jump_to_definition_with_forward_path_stitching.rs, stack-graphs/tests/it/json.rs, tree-sitter-stack-graphs/src/cli/analyze.rs, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/test.rs, tree-sitter-stack-graphs/tests/it/test.rs
This PR makes several changes to make partial path computation + path stitching the preferred and default method to do resolution. Several larger and smaller changes make this possible:
- Tests switched from using regular path search to partial path finding. Test assertions now use stitching.
- `PartialPaths::find_all_partial_paths_in_file` has been replaced by `PartialPaths::find_minimal_partial_paths_set_in_file`. The new method computes a much smaller set of partial paths.
- The `ForwardPartialPathStitcher::find_locally_complete_partial_paths` method replicates the old `PartialPaths::find_minimal_partial_paths_set_in_file` behavior by stitching the minimal set. This method is used in several places to control the transition from the old to the new method. For example, it is used in …
=> More partial path finding improvements

languages/tree-sitter-stack-graphs-typescript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-typescript/test/expressions/asserts-condition.ts, languages/tree-sitter-stack-graphs-typescript/test/expressions/asserts-type.ts, tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/src/cli/analyze.rs, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/cli/util.rs
Some small updates to the `analyze` command and the TypeScript TSG:
- A few syntax cases were added in the TSG, as well as corresponding tests.
- Output of `test` and `analyze` in debug builds includes the runtime per file.
- The `--hide-failure-errors` flag was renamed to the more descriptive `--hide-error-details`, which is now supported by the `test` and `analyze` commands.
- Files in directory arguments (e.g. when `test/` is passed) are now processed in filename order.
=> Updates to `analyze` (and `test`)

.github/workflows/publish-tree-sitter-stack-graphs-java.yml
This PR adds a new release action for our Java tssg crate. This action is based on other release actions in this repo.
It will run on tag push, so I plan to exercise this action when I push up the tag `tree-sitter-stack-graphs-java-v0.1.0`, which will include all the changes linked [here](https://github.com/github/stack-graphs/compare/tree-sitter-stack-graphs-typescript-v0.1.0...main).
=> Add action for Java tssg releases

languages/tree-sitter-stack-graphs-java/Cargo.toml
Updates the `tree-sitter-java` crate to the latest version, 0.20.0. 😄 
This explicit specification of a version is required for publishing the `tree-sitter-stack-graphs-java` crate, as noted in the failed run [here](https://github.com/github/stack-graphs/actions/runs/4148507907/jobs/7176561630#step:5:14).
=> Specify tree-sitter-java crate version

tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/src/cli/init.rs
The `tree-sitter-stack-graphs` crate depends on `chrono` to get the current year in the CLI. Latest `chrono` version has a vulnerability, but there's no release yet that fixes this. [Online comments](https://github.com/chronotope/chrono/issues/602#issuecomment-1436548077) suggest that the `chrono` project has trouble with maintainance and getting to new releases.
This PR removes the `chrono` dependency and replaces it with `time`, which sees releases more often. Much of `time` is also behind feature flags, so we pull in less code as well.
=> Replace chrono dependency by time

stack-graphs/CHANGELOG.md, stack-graphs/src/c.rs, stack-graphs/src/partial.rs, stack-graphs/tests/it/can_find_local_nodes.rs, stack-graphs/tests/it/can_find_node_partial_paths_in_database.rs, stack-graphs/tests/it/can_find_partial_paths_in_file.rs, stack-graphs/tests/it/can_find_root_partial_paths_in_database.rs, stack-graphs/tests/it/can_jump_to_definition_with_forward_partial_path_stitching.rs, stack-graphs/tests/it/can_jump_to_definition_with_forward_path_stitching.rs, stack-graphs/tests/it/json.rs, tree-sitter-stack-graphs/src/cli/analyze.rs, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/test.rs, tree-sitter-stack-graphs/tests/it/test.rs
This PR fixes a few issues related to tests:
- Rename "partial paths set" to "partial path set". The set already implies multiple.
- Tests were still doing path finding, even though the caller was responsible for that now. Removed that code.
- Add a flag to disable builtins for tests, which can help with debugging.
=> Small fixes for tests and partial paths

stack-graphs/src/partial.rs, tree-sitter-stack-graphs/src/cli/util.rs
Path concatenation requires pre- and postconditions to be half-open to account for the effect of the join node, which is present on both sides. This logic is part of the `concatenate` method. This PR factors that out into a separate method, which makes the code cleaner and allows reuse in a later PR.
=> Refactor pre- and postcondition manipulation

stack-graphs/Cargo.toml, stack-graphs/src/cycles.rs, stack-graphs/src/partial.rs, stack-graphs/src/paths.rs, stack-graphs/src/stitching.rs, stack-graphs/tests/it/c/can_jump_to_definition_with_phased_partial_path_stitching.rs, stack-graphs/tests/it/can_jump_to_definition_with_forward_partial_path_stitching.rs, stack-graphs/tests/it/cycles.rs, stack-graphs/tests/it/json.rs, stack-graphs/tests/it/partial.rs, stack-graphs/tests/it/util.rs
When testing https://github.com/github/stack-graphs/pull/193#issuecomment-1442133780, it turned out that the condition for cyclicity was incorrect. In particular, depending on the kind of path construction that happened, we need a different condition.
The old condition allowed cycles with compatible stacks if the precondition was strengthened, that is, when following the cycle consumes symbols from the stack _before_ the cycle. The idea is that eventually those symbols will all be consumed, ensuring termination. However, this is not true when constructing paths that allow their precondition to grow, such as `find_minimal_patial_path_set` does. In those cases, the cycle can be followed arbitrarily many times. In cases where the precondition is fixed, such as when finding complete paths, it …
=> Non-terminating path finding with current definition of `is_productive`

languages/tree-sitter-stack-graphs-java/rust/lib.rs, languages/tree-sitter-stack-graphs-java/src/stack-graphs.tsg
Adds `PROJECT_NAME_VAR` and `FILE_PATH_VAR` to the Java rust lib.
=> Set global variables for Java tssg

languages/tree-sitter-stack-graphs-typescript/src/stack-graphs.tsg, stack-graphs/src/partial.rs
Currently, a path's scope stack postcondition must be empty for the path to be considered complete. This means arguments to function or type applications _must_ be used before a path can become complete. This condition is in my opinion too strict.
An example of a situation that doesn't work well with this behavior is the following:
```typescript
class A<T> {
m(): T;
}
function test(a: A<{ i: number }>) {
a.m().i;
//    ^ defined: 2
}
```
The reference to `m` is not resolved, because the type argument `string` is still on the scope stack. The reference to `i` resolves fine again, because the type argument has been consumed by then.
I think removing the linearity restriction is the right thing to do here. The effect of the change is limited to precisely these situations. This is also …
=> Do not require scope stack linearity

languages/tree-sitter-stack-graphs-java/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-java/test/statement/for_statement.java
Updates for statement rules + tests.
Fixes https://github.com/github/stack-graphs/issues/221.
Thank you @robrix for showing me the way with this one 💪🏻
=> Update for statement tests

languages/tree-sitter-stack-graphs-java/Cargo.toml
Updates Java crate version to 0.2.0 to support the latest release: https://github.com/github/stack-graphs/pull/231
=> Update Java tssg crate version

stack-graphs/src/graph.rs, tree-sitter-stack-graphs/src/cli.rs, tree-sitter-stack-graphs/src/cli/visualize.rs
Adds a new `visualize` command that takes file paths and generates a visualization for the given files. Won't scale to many files, definitely not to a whole repo, but should be very useful to debug specific problems in larger repos.
Use handles in the serialization for file references, instead of the strings themselves. Currently the JSON data becomes very big, especially when long files names are involved.
=> Generate visualization from database

stack-graphs/src/graph.rs, tree-sitter-stack-graphs/src/loader.rs
Ensure that `StackGraph` and `LanguageConfiguration` can be shared in concurrent contexts.
=> Improve sharing of stack graphs and language configurations

languages/tree-sitter-stack-graphs-java/rust/bin.rs, languages/tree-sitter-stack-graphs-java/rust/lib.rs, languages/tree-sitter-stack-graphs-java/rust/test.rs, languages/tree-sitter-stack-graphs-typescript/rust/bin.rs, languages/tree-sitter-stack-graphs-typescript/rust/lib.rs, languages/tree-sitter-stack-graphs-typescript/rust/npm_package.rs, languages/tree-sitter-stack-graphs-typescript/rust/test.rs, languages/tree-sitter-stack-graphs-typescript/rust/tsconfig.rs, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/src/cli.rs, tree-sitter-stack-graphs/src/cli/analyze.rs, tree-sitter-stack-graphs/src/cli/init.rs, tree-sitter-stack-graphs/src/cli/load.rs, tree-sitter-stack-graphs/src/cli/parse.rs, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/cli/util.rs, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/loader.rs, tree-sitter-stack-graphs/src/util.rs, tree-sitter-stack-graphs/tests/it/main.rs, tree-sitter-stack-graphs/tests/it/nodes.rs, tree-sitter-stack-graphs/tests/it/test.rs
This PR improves various error messages that are reported by the CLI.
- Most error types now have a `display_pretty` method, which uses the `display_pretty` methods from TSG when they exist.
- The language specific libraries have a new `try_language_configuration` which doesn't panic but gives back the error to the user, allowing them to print it nicely if we are in a console context. This is used by the CLI and test runner to print a nice error when there are problems with the TSG, instead of the obscure panic it used to be.
=> Improve CLI reported errors

.vscode/launch.json, .vscode/tasks.json, languages/tree-sitter-stack-graphs-java/rust/bin.rs, languages/tree-sitter-stack-graphs-typescript/Cargo.toml, languages/tree-sitter-stack-graphs-typescript/rust/bin.rs, languages/tree-sitter-stack-graphs-typescript/vscode/.gitignore, languages/tree-sitter-stack-graphs-typescript/vscode/package-lock.json, languages/tree-sitter-stack-graphs-typescript/vscode/package.json, languages/tree-sitter-stack-graphs-typescript/vscode/src/extension.ts, languages/tree-sitter-stack-graphs-typescript/vscode/tsconfig.json, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/src/bin/tree-sitter-stack-graphs/main.rs, tree-sitter-stack-graphs/src/ci.rs, tree-sitter-stack-graphs/src/cli.rs, tree-sitter-stack-graphs/src/cli/clean.rs, tree-sitter-stack-graphs/src/cli/database.rs, tree-sitter-stack-graphs/src/cli/index.rs, tree-sitter-stack-graphs/src/cli/init.rs, tree-sitter-stack-graphs/src/cli/lsp.rs, tree-sitter-stack-graphs/src/cli/parse.rs, tree-sitter-stack-graphs/src/cli/query.rs, tree-sitter-stack-graphs/src/cli/test.rs
| ◀️ #248 | #251 ▶️ |
|-|-|
This PR is part of the work to implement an LSP server (#242). This adds a noop LSP server and a VSCode plugin that uses it. This is just to get the scaffolding up, implementing the actual behavior will be done in follow-up PRs.
This PR implements the LSP server for `tree-sitter-stack-graphs-typescript`. This is because several configuration details (such as file extensions, language names) need to be replicated in the VSCode plugin `package.json`. This makes it a little difficult to set up the code such that we can easily have dedicated VSCode plugins for different languages as we can for the CLI itself.
I'm not sure yet what the best way to do that is. The main options I see are (a) using some templating in the VSCode plugin build, or (b) add a `vscode` …
=> Add skeleton LSP server and VSCode extension

languages/tree-sitter-stack-graphs-typescript/vscode/package-lock.json, languages/tree-sitter-stack-graphs-typescript/vscode/package.json, languages/tree-sitter-stack-graphs-typescript/vscode/src/extension.ts, stack-graphs/src/storage.rs, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/src/cli/index.rs, tree-sitter-stack-graphs/src/cli/lsp.rs, tree-sitter-stack-graphs/src/cli/query.rs, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/cli/util.rs, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/util.rs
| ◀️ #238 | #254 ▶️ |
|-|-|
This PR is part of the work to implement an LSP server (#242). This adds indexing of the workspace folders.
- Indexing is done in a background thread, so that the LSP server is not blocked for too long, which might make the client nervous.
- Cancellation flags were cleaned up a bit. Instead of exposing the usize required by Tree-sitter in the trait, we handle the bridging implcitly. This makes it easier to write combinators that combine different cancellation flags.
- Some timeout flags and VSCode extension config were added to control the indexing from the plugin.
- The indexing runs whenever workspace folders change.
Indexing is not particulary fast. A few things were applied that should make it faster:
- Do not check foreign keys all the time.
- Do not do …
=> Implement indexing in the LSP server

stack-graphs/src/storage.rs, tree-sitter-stack-graphs/src/cli.rs, tree-sitter-stack-graphs/src/cli/index.rs, tree-sitter-stack-graphs/src/cli/query.rs, tree-sitter-stack-graphs/src/cli/status.rs
| ◀️ #254 | #256 ▶️ |
|-|-|
This PR is part of the work to implement an LSP server (#242). It changes the database so that we can record indexing failures. A new `status` command shows the status of files in the database. This is helpful for debugging.
The command does not yet report on files that are present on the file system but missing from the database.
=> Introduce `status` command

languages/tree-sitter-stack-graphs-typescript/vscode/package.json, languages/tree-sitter-stack-graphs-typescript/vscode/src/extension.ts, stack-graphs/src/storage.rs, tree-sitter-stack-graphs/src/cli/lsp.rs, tree-sitter-stack-graphs/src/cli/query.rs, tree-sitter-stack-graphs/src/cli/util.rs
| ◀️ #255 | #257 ▶️ |
|-|-|
This PR is part of the work to implement an LSP server (#242). This implements LSP Go to Definition.
It is very slow. Too slow to be very useful at the moment.
The obvious thing to look at next would be some kind of caching. Each query will load everything fresh from disk. But the LSP server is persistent between queries, so we can keep the things we load around. This brings its own set of problems, of course. This cache can become (partially) invalid when files are changed, and the stack graph data structures are not built for removing information.
Preloading the data for a file when it is opened in an editor would also help, I expect.
=> Implement LSP Go to Definition

tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/src/cli/lsp.rs, tree-sitter-stack-graphs/src/cli/query.rs, tree-sitter-stack-graphs/src/cli/util.rs
| ◀️ #256 | #259 ▶️ |
|-|-|
This PR improves the console output for the `query` command by displaying source excerpts when possible.
Before:
After, for a single reference at the given location:
After, for multiple references at the given location:
=> Show source excerpts for resolved definitions

stack-graphs/src/serde/partial.rs, stack-graphs/src/storage.rs
| ◀️ #257 | #260 ▶️ |
|-|-|
This PR contains several fixes for the SQLite database storage:
- Include the node id to only load paths for a given node. Before paths were loaded multiple times.
- If a symbol stack prefix was already loaded, only skip that prefix, but still try the remaining prefixes.
- Swap path storage conditions, because `is_root` implies `is_in_file`, resulting in all files being stored in the `file_paths` table, and none in the `root_paths` table.
- Deserialize stack variables, which were completely ignored.
=> Storage fixes

tree-sitter-stack-graphs/src/cli/index.rs, tree-sitter-stack-graphs/src/cli/query.rs, tree-sitter-stack-graphs/src/cli/status.rs
| ◀️ #259 | #261 ▶️ |
|-|-|
This PR ensures that CLI commands always use canonical paths.
=> Use canonical paths for CLI commands

languages/tree-sitter-stack-graphs-java/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-typescript/src/stack-graphs.tsg, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/tests/it/nodes.rs
Include goodies from the latest TSG release.
The TSG changes are renames of unused captures, so they are not considered errors.
=> Update tree-sitter-graph to v0.10

.github/workflows/ci.yml, languages/tree-sitter-stack-graphs-java/Cargo.toml, languages/tree-sitter-stack-graphs-typescript/Cargo.toml, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/src/cli/clean.rs, tree-sitter-stack-graphs/src/cli/database.rs, tree-sitter-stack-graphs/src/cli/index.rs, tree-sitter-stack-graphs/src/cli/init.rs, tree-sitter-stack-graphs/src/cli/init/license.rs, tree-sitter-stack-graphs/src/cli/lsp.rs, tree-sitter-stack-graphs/src/cli/parse.rs, tree-sitter-stack-graphs/src/cli/query.rs, tree-sitter-stack-graphs/src/cli/status.rs, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/cli/util.rs
This PR introduces a couple of changes related to project setups.
- Some projects would use an on-by-default `test` feature. This is replaced with with `dev-dependencies`. This ensures that tests are run without having to specify a feature, but without _always_ pulling in those dependencies for crate users.
- The `tree-sitter-stack-graphs init` command now supports a `--internal` flag that generates a project with the right configuration to line inside this repository. For example, they include the path in dependencies, and use the right license header.
- A new CI job tests that new projects generated by `tree-sitter-stack-graphs init` compile without errors.
I ended up upgrading `clap` to version 4, so some of the changes are due to that.
=> Updates to language project structure

tree-sitter-stack-graphs/src/cli/test.rs
When upgrading `clap`, the range for `num_args` was accidentally set to the empty `0..1`. This changes this to `0..=1` which allows the indended zero or one arguments.
=> Fix empty range for num_args

tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/src/cli.rs, tree-sitter-stack-graphs/src/cli/match.rs, tree-sitter-stack-graphs/src/cli/parse.rs
This PR adds a `match` command that runs stanza queries against a given source file and outputs the results to the console.
The output tries to strike a balance between giving enough information to quickly get an idea of what's going on, allow easy follow up, and not be too verbose. In particular:
- The stanza queries are identified only by their source position, but the source is not shown. This is the choice I'm least sure about. But queries are often spread over multiple lines and can be quite long, so I'm afraid showing them might result in very verbose output. In particular because queries are not matched in source order, but in AST traversal order. In other words, the same query can be part of the output many times.
- The top-level matched node, as well as all captures are shown as …
=> Add `match` command to run stanza queries

languages/tree-sitter-stack-graphs-typescript/rust/util.rs, stack-graphs/src/graph.rs, stack-graphs/src/serde/graph.rs, stack-graphs/src/visualization.rs, stack-graphs/src/visualization/visualization.js, stack-graphs/tests/it/serde.rs, stack-graphs/tests/it/test_graphs/simple.rs, tree-sitter-stack-graphs/src/lib.rs
This PR adds support for edge debug information and loads debug attributes from the TSG graph. As a result, edges in the visualization will be annotated with the location of the `edge` statement that created it.
Additionally, a bug is fixed which caused too many nodes to be included in the generated visualization.
=> Include edge debug information in visualization

stack-graphs/src/visualization/visualization.css, stack-graphs/src/visualization/visualization.js
This PR fixes an issue where the visualization would only display the stacks for the current path for the last time the path crossed that node. If the node was used multiple times, the stacks for earlier uses would be lost.
Additionally, font sizes were a bit tweaked to allow for the display of more information.
=> Display stacks for each time a path crosses a node

tree-sitter-stack-graphs/src/cli/index.rs, tree-sitter-stack-graphs/src/cli/match.rs, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/cli/util.rs, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/loader.rs, tree-sitter-stack-graphs/tests/it/loader.rs
| ◀️ #260 | #262 ▶️ |
|-|-|
This PR ensures that special files (those that are relevant for a language, but not written in that language, such as `tsconfig.json`) are always indexed.
Previously, the language loader only returned the primary language of a file (i.e., the language the file is written in). These changes return the primary, as well as any secondary languages (i.e., languages for which the file is special). The indexer makes sure that all languages get their change to generate stack graph for the file.
I have wondered (again) whether there should be a difference between primary and secondary languages at all. I think that still makes sense for the following reasons:
1. The contributions of a secondary language are typically not relevant when navigating the file. They are only …
=> Ensure special files are also indexed

stack-graphs/CHANGELOG.md, stack-graphs/include/stack-graphs.h, stack-graphs/src/c.rs, stack-graphs/src/graph.rs, stack-graphs/src/serde/graph.rs, stack-graphs/tests/it/c/nodes.rs, stack-graphs/tests/it/test_graphs/simple.rs
This adds a `fully_qualified_name` field to `SourceInfo` to provide a convenient mechanism for labeling stack graph nodes with a fully qualified name. No facilities for generating a fully qualified name are provided in this change set, this only allows for tracking of fully qualified names via a stack graph node's associated `SourceInfo`.
=> Add `fully_qualified_name` field to `SourceInfo`

stack-graphs/src/storage.rs
| ◀️ #262 |
|-|
Per @dcreager's [suggestion](https://github.com/github/stack-graphs/pull/254#discussion_r1171680601), this PR replaces explicit `BEGIN`/`COMMIT` with the `transaction()` mechanism of Rusqlite. This should result in more robust behavior when errors occur, because the open transaction is rolled back as soon as the transaction object is dropped.
=> Use transaction mechanism instead of explicit BEGIN/COMMIT

stack-graphs/CHANGELOG.md, stack-graphs/include/stack-graphs.h, stack-graphs/src/assert.rs, stack-graphs/src/c.rs, stack-graphs/src/cycles.rs, stack-graphs/src/partial.rs, stack-graphs/src/stitching.rs, stack-graphs/src/storage.rs, stack-graphs/tests/it/can_find_local_nodes.rs, stack-graphs/tests/it/can_find_node_partial_paths_in_database.rs, stack-graphs/tests/it/can_find_partial_paths_in_file.rs, stack-graphs/tests/it/can_find_root_partial_paths_in_database.rs, stack-graphs/tests/it/can_jump_to_definition.rs, stack-graphs/tests/it/can_jump_to_definition_with_forward_partial_path_stitching.rs, stack-graphs/tests/it/cycles.rs, stack-graphs/tests/it/partial.rs, stack-graphs/tests/it/serde.rs, stack-graphs/tests/it/util.rs, tree-sitter-stack-graphs/src/cli/index.rs, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/tests/it/test.rs
Path finding (`PartialPath::find_minimal_path_set`) and path stitching (`ForwardPartialPathSticher::find_all_complete_partial_paths`) have very similar structures, only they append edges and partial paths respectively.  This PR aims to unify these two implementations to get something that is easier to maintain, and allows more flexibility and how path building is set up.
- The `Appendable<Ctx>` trait dealt with two concerns: (1) abstracting over things that could be appended to a partial path, and (2) keep track of the context where we could convert handles into these things. In the new setup, `Appendable` only deals with (1), while a new `ToAppendable` trait is responsible for (2).
- The `ForwardPartialPathStitcher` is now abstract in the database and the concrete appendable that is used …
=> Unify path finding and path stitching

stack-graphs/CHANGELOG.md, stack-graphs/Cargo.toml, stack-graphs/src/storage.rs
Database access (particularly writing, it seems) is fairly slow. Currently the database is populated with JSON objects, which are pretty verbose. This PR changes that to use messagepack values, which are binary and optimized for small size, if I understand things correctly.
A rough comparison of index times shows a speedup of almost 2x for some files and a database size reduction of almost 3x. The time reduction is more pronounced for smaller files, probably because more of the index work is writing the data, compared to computing it.
=> Store messagepack values in database instead of JSON

languages/tree-sitter-stack-graphs-typescript/rust/tsconfig.rs, languages/tree-sitter-stack-graphs-typescript/test/projects/invalid-paths-mappings.ts
The `TsConfigAnalyzer` would panic on certain invalid path mappings. This PR makes the analyzer more resilient, and adds a test to check that these cases do not cause panics anymore.
=> Make TsConfigAnalyzer more resilient against invalid path mappings

languages/tree-sitter-stack-graphs-java/Cargo.toml
**PR Summary**:
PR simply updates the homepage of `tree-sitter-stack-graphs-java`. Current location is [broken](https://github.com/github/stack-graphs/tree/main/stack-graphs/languages/tree-sitter-stack-graphs-java). Relevant Crates page can be found [here](https://crates.io/crates/tree-sitter-stack-graphs-java).
=> fix: update tree-sitter-stack-graphs-java homepage in manifest

.github/workflows/perf.yml
Now that #303 is merged, we can change base branch CI job to use local data as well. (THis wasn't there before #303, so only the head branch used it in that PR.)
=> Use new data for base branch perf job too

AUTHORS, stack-graphs/src/storage.rs
In #306 it's reported that SQLite is slow.  This adds indexes so lookups will be faster.  The intention is to speed up the bottom 3 queries from https://github.com/github/stack-graphs/issues/306#issuecomment-1665402600 as they are "the ones to focus on".
Specifically this should speed up:
> * Load graph data for a file
>
>         SELECT value FROM graphs WHERE file = ?
>
>   Called many times during path stitching
>
> * Load paths for a file node
>
>         SELECT file,value from file_paths WHERE file = ? AND local_id = ?
>
>   Called many times during path stitching.
>
> * Load paths for root node
>
>         SELECT file, value from root_paths WHERE symbol_stack = ?
>
>   Called many times during path stitching.
If the data that you're fetching is in the index then SQLite won't even …
=> Storage: Add Indexes for common queries

Cargo.toml, stack-graphs/Cargo.toml, tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/src/cli.rs, tree-sitter-stack-graphs/src/cli/index.rs, tree-sitter-stack-graphs/src/cli/lsp.rs, tree-sitter-stack-graphs/src/cli/parse.rs, tree-sitter-stack-graphs/src/cli/query.rs, tree-sitter-stack-graphs/src/cli/status.rs, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/cli/util.rs, tree-sitter-stack-graphs/src/cli/util/reporter.rs
Fixes https://github.com/github/stack-graphs/issues/307 by introducing a public `Reporter` trait that users can implement for custom logging.
File status is reported through a `Reporter` trait. To keep the burden on implementors limited, we require a predicatable way of calling reporters:
- files can be skipped, indicated by a single call to `skipped`, or
- files are processed, indicated by a pair of calls to `started` and on of (`succeeded`, `failed`, or `canceled`).
- A `ConsoleReporter` type is provided that prints to the console and allows control over what is logged.
- The implementations if `Indexer` and `Querier` take some short-cuts, and violate this protocol. That is solved by the `CLIFileLogger` utility class, that retains that part of the logic from the old `Logger` …
=> Introduce new public `Reporter` trait that is used from CLI types to report file status

stack-graphs/CHANGELOG.md, stack-graphs/src/assert.rs, stack-graphs/src/c.rs, stack-graphs/src/stitching.rs, stack-graphs/src/storage.rs, stack-graphs/tests/it/can_jump_to_definition.rs, stack-graphs/tests/it/can_jump_to_definition_with_forward_partial_path_stitching.rs, stack-graphs/tests/it/cycles.rs, tree-sitter-stack-graphs/src/cli/query.rs, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/cli/visualize.rs
This PR makes changes to `ForwardPartialPathStitcher` and related types to add support for running the path stitcher directly on a `SQLiteReader`. With this change, the `ForwardPartialPathStitcher` is the one and only path building implementation.
Some changes that were made as part of this:
- Rename `Candidates` to `ForwardCandidates`, which is in line with the `ForwardPartialPathStitcher` and would make it easier in the future if we ever get backward algorithms.
- Add `SQLReader::clear` method for easier reuse of instances. It clears the cached data in the reader.
- Extend `ForwardCandidates` trait with the reponsibility to manage access to the graph and partial path arena. As a result, the `ForwardCandidates` instance is the only thing going into the stitcher, and replaces the explicit …
=> Allow path stitcher to work on `SQLiteReader`

languages/tree-sitter-stack-graphs-java/Cargo.toml, languages/tree-sitter-stack-graphs-typescript/Cargo.toml
Tree-sitter grammar versions are not semantic. Therefore, we depend on precise versions and don't allow e.g. a new patch version to break our code.
For example, the latest tree-sitter-typescript release (a patch bump) broke our build because the grammar nodes changed and queries became invalid.
=> Fix grammar versions

tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/tests/it/nodes.rs
This PR adds support for `syntax_type` and `definiens_node` attributes and sets the corresponding values in the source info.
=> Add support for `syntax_type` and `definiens_node`

stack-graphs/src/stitching.rs
Similar path detection prevents exponential path blowup during path stitching. However, it incurs a preformance cost and for that reason it was disabled by default.
The problem is that users cannot pass along the right stitcher configuration in all places where stitching is used. If the rules for a language can result in exponential blowup, users have no way of preventing that at the moment.
This PR changes the partial path stitcher to use similar path detection by default. This will make the library safe and unblock other work depending on this to work. In the future, users should be able to pass along stitcher configuration everywhere it is relevant. This work is tracked in issue #322.
=> Enable similar path detection by default

stack-graphs/src/cycles.rs, stack-graphs/src/stitching.rs
The similar path detector was ignoring shadowing behavior. This PR fixes that by ensuring that if two paths are equivalent but one shadows the other, we pick the shadowing one.
=> Prefer higher-priority similar paths

languages/tree-sitter-stack-graphs-typescript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-typescript/test/modules/import-reexports-from-subdirectory-index.ts, languages/tree-sitter-stack-graphs-typescript/test/modules/import-reexports-from-superdirectory-index.ts
Star reexports from index files could lead to "free" cycles that would be rejected by the cycle detector. For example, `export * from './mod'` in `foo/index.ts` meant that `foo` could be rewritten to `foo/mod` even when `foo` was not the last component. So, `foo/mod` could become `foo/mod/mod`, etc. By ensuring that the jump from `foo` to `foo/mod` is only allowed when there are remaining symbols on the stack, this behavior is prevented.
Thanks to @scola84 for reporting this issue!
=> Fix free cycle for index files

languages/tree-sitter-stack-graphs-typescript/src/stack-graphs.tsg
Small fix with the definitions created for async constructs to ensure we don't accidentally treat the whole async construct as a definition.
=> Reduce source span for async definitions

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-javascript/test/base_syntax.js, languages/tree-sitter-stack-graphs-javascript/test/jsx/jsx_core.js, languages/tree-sitter-stack-graphs-javascript/test/jsx/jsx_fragment.js, languages/tree-sitter-stack-graphs-javascript/test/jsx/jsx_namespace_name.js, languages/tree-sitter-stack-graphs-javascript/test/jsx/jsx_self_closing_element.js, languages/tree-sitter-stack-graphs-javascript/test/jsx/jsx_text.js
This PR adds support for JSX nodes.
=> Add JSX Support

stack-graphs/src/visualization/visualization.css, stack-graphs/src/visualization/visualization.js
Change the color scheme for stack graph visualizations to color nodes by file. This should make debugging multi-file tests easier. References and definitions will have the same color (if from the same file), but the node shape still indicates what it is.
=> Color nodes by file

stack-graphs/src/visualization/visualization.css, stack-graphs/src/visualization/visualization.js
A few small improvements to the visualizaton:
- Add file legend (can be toggeled by pressing `f`).
- Make border of clickable nodes heavier. I tried @dcreager's [suggestion](https://github.com/github/stack-graphs/pull/343#pullrequestreview-1722716248) to lighten non-clickable nodes compared to clickable (definition, reference) nodes. I found that this would make clickable nodes very light and the graph structure became harder to see. This change will hopefully make it still easier to find clickable nodes, even when zoomed out more.
=> More visualization changes

languages/tree-sitter-stack-graphs-typescript/rust/npm_package.rs, languages/tree-sitter-stack-graphs-typescript/rust/tsconfig.rs, languages/tree-sitter-stack-graphs-typescript/test/packages/can-access-package-non-main-explicilty.ts, languages/tree-sitter-stack-graphs-typescript/test/packages/package-does-not-export-non-main.ts, languages/tree-sitter-stack-graphs-typescript/test/packages/package-exports-explicit-main.ts, languages/tree-sitter-stack-graphs-typescript/test/packages/package-invisible-without-dependency.ts, languages/tree-sitter-stack-graphs-typescript/test/packages/package-main-defaults-to-index.ts
Similar to `tree-sitter-stack-graphs-javascript`, this PR add support for the `main` attribute in `package.json` files.
If a `main` module is specified, the exports of that module are accessible directly from the package name. If it is unspecified, we default to `index` as Node does.
=> Support main module configuration in `package.json`

stack-graphs/src/arena.rs, stack-graphs/tests/it/arena.rs
The `.clear()` methods would lose the element at position 0, which could lead to panics. This PR fixes that.
=> Fix arena clear methods

languages/tree-sitter-stack-graphs-javascript/rust/npm_package.rs, languages/tree-sitter-stack-graphs-javascript/rust/util.rs, languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-javascript/test/old/bug_regressions/variable_resolves_to_module.js
« #340
Module names were not guarded, which led to a situation where variable names could resolve to a module name.
This PR changes that and ensures module names are always guarded by `GUARD:MODULE`, preventing this bug.
A new bug regression tests has been added to test for this case.
=> Guard module names

stack-graphs/src/stitching.rs, stack-graphs/src/storage.rs, stack-graphs/tests/it/can_find_root_partial_paths_in_database.rs, stack-graphs/tests/it/main.rs, stack-graphs/tests/it/stitching.rs, stack-graphs/tests/it/storage.rs
« #349
This PR makes changes to the loading of candidate paths from the root node:
- It ensure valid candidate paths that were previously missing are included.
- It makes the lookups more precise by considering the absence or presence of variables in the symbol stacks.
When finding candidate paths from root for a given symbol stack postcondition, any root path with a symbol stack precondition matching (a prefix) of the symbols in the postcondition was selected.
This has two issues:
- _**Incorrect:**_ It would not consider paths with a precondition that _extends_ the postcondition. However, if the postcondition has a variable, it can unify with extensions of the postcondition symbols as well. _This has probably not been a huge problem in practice, because we have used stitching mostly for …
=> Fix root paths candidates

languages/tree-sitter-stack-graphs-java/Cargo.toml, languages/tree-sitter-stack-graphs-java/rust/lib.rs, languages/tree-sitter-stack-graphs-javascript/rust/lib.rs, languages/tree-sitter-stack-graphs-typescript/rust/lib.rs, stack-graphs/include/stack-graphs.h, stack-graphs/src/assert.rs, stack-graphs/src/c.rs, stack-graphs/src/stitching.rs, stack-graphs/tests/it/c/can_find_local_nodes.rs, stack-graphs/tests/it/c/can_find_partial_paths_in_file.rs, stack-graphs/tests/it/c/can_find_qualified_definitions_with_phased_partial_path_stitching.rs, stack-graphs/tests/it/c/can_jump_to_definition.rs, stack-graphs/tests/it/c/can_jump_to_definition_with_phased_partial_path_stitching.rs, stack-graphs/tests/it/can_find_local_nodes.rs, stack-graphs/tests/it/can_find_node_partial_paths_in_database.rs, stack-graphs/tests/it/can_find_partial_paths_in_file.rs, stack-graphs/tests/it/can_find_root_partial_paths_in_database.rs, stack-graphs/tests/it/can_jump_to_definition.rs, stack-graphs/tests/it/can_jump_to_definition_with_forward_partial_path_stitching.rs, stack-graphs/tests/it/cycles.rs, stack-graphs/tests/it/serde.rs, tree-sitter-stack-graphs/src/cli/index.rs, tree-sitter-stack-graphs/src/cli/init.rs, tree-sitter-stack-graphs/src/cli/query.rs, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/cli/visualize.rs, tree-sitter-stack-graphs/src/loader.rs, tree-sitter-stack-graphs/src/test.rs, tree-sitter-stack-graphs/tests/it/loader.rs, tree-sitter-stack-graphs/tests/it/test.rs
« #346 | #326 »
The static methods on `ForwardPartialPathStitcher` do not allow configuration of stitcher properties. This PR adds a `StitcherConfig` type to remedy that.
=> Add support for stitcher configuration

stack-graphs/src/cycles.rs, stack-graphs/src/graph.rs, stack-graphs/src/lib.rs, stack-graphs/src/stats.rs, stack-graphs/src/stitching.rs, stack-graphs/src/storage.rs, stack-graphs/tests/it/main.rs, stack-graphs/tests/it/stats.rs, tree-sitter-stack-graphs/src/cli/index.rs, tree-sitter-stack-graphs/src/cli/query.rs, tree-sitter-stack-graphs/src/cli/util.rs
« #321
Adds stats collection during stitching and in the storage reader. This is a first step to making the behavior of the algorithms more visible. This could be useful to understand performance, and e.g. compare the effect of using different path sets for resolution.
The stats can be printed from the CLI's `index` and `query` commands by passing `--stats`. They look as follows:
```
stitching stats      |   min   |   p25   |   p50   |   p75   |   max   |  total  
---------------------------+---------+---------+---------+---------+---------+---------
queued paths per phase    |       1 |       1 |       3 |       4 |      11 |      22 
processed paths per phase |       1 |       3 |       5 |      80 |    1343 |      22 
accepted path length      |      93 |      93 |      93 |     157 | …
```
=> Collect stitching and database stats

languages/tree-sitter-stack-graphs-typescript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-typescript/test/expressions/rest-array-attern.ts, languages/tree-sitter-stack-graphs-typescript/test/expressions/satisfies-type.ts, languages/tree-sitter-stack-graphs-typescript/test/expressions/undefined-pattern.ts, languages/tree-sitter-stack-graphs-typescript/test/modules/reexport-as-object.ts, languages/tree-sitter-stack-graphs-typescript/test/modules/very-deep-namespace.ts, languages/tree-sitter-stack-graphs-typescript/test/statements/class-static-block.ts
This PR fixes many issues that were causing executione errors in production because of duplicate or missing scoped variables.
- Support `satisfies` expression
- Fix bug in reexport as module
- Eliminate nested identifier unrolling. This change is a bit bigger, because I've replaced the manual unrolling we did previously with top-level `(nested_identifier)` rules, so we support arbitrarily deep nested identifiers now. This comes at the cost of sometimes having extra, unused, bits in the graph.
- Fix missing scoped variable on undefined as pattern
- Fix rest array pattern crash
- Add support for class static blocks
_Can be reviewed commit-by-commit._
=> Fix TypeScript execution errors in production

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg
This PR removes extraneous edges in the graphs for `new_expression`. This was causing a bug in the VEA Living Spec test case https://github.com/github/living-spec-vea/tree/main/vulnerabilities_in_class_definition. Once this PR is merged, that test should pass as expected.
=> Remove Extraneous New Expr Edges

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-javascript/test/base_syntax.js
This PR resolves parameter-covalue errors when comments occur in parameter lists. It partially addresses https://github.com/github/aleph/issues/3205.
=> Comments in param lists

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-javascript/test/base_syntax.js
This PR addresses errors arising in `if`/`else` blocks when comments are added around the keywords. It partially fixes https://github.com/github/aleph/issues/3205.
=> Comments around keywords in `if`

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg
This seems to pass the tests on the aleph side, solving one of the P0 bugs. No other test changes there were required.
=> Makes class definiens be the constructor instead of the class body

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-javascript/test/computation_flow/class_declaration_fields_and_methods_visible_in_other_methods.js
Makes `this` refer correctly in class definitions, making the following test pass:
```javascript
class Foo {
bar = 1;
baz() { }
quux() {
this.bar;
//   ^ defined: 2
this.baz();
//   ^ defined: 3
}
}
(class {
bar = 1;
baz() { }
quux() {
this.bar;
//   ^ defined: 14
this.baz();
//   ^ defined: 15
}
});
```
=> 'this' in class methods can see the methods and fields

languages/tree-sitter-stack-graphs-python/Cargo.toml, languages/tree-sitter-stack-graphs-python/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-python/test/imports/import_submodule_aliased.py, languages/tree-sitter-stack-graphs-python/test/pattern_matching.py
« #282
Changes the rules as follows:
- Support the latest Python grammar release.
- Be more precise about which identifiers are definitions.
- Fix some import cases.
The rules were introducing definitions for all identifiers, regardless of whether they appeared in a definition context. This made the rules easy, but results in unexpected behavior in the UI, because every reference is now also a definition and included in the results for that reference.
Interestingly, this worked in the old DSL because the graph was pruned, so unconnected definitions would just disappear!
To fix this, the rules must be more specific about which identifiers should actually give rise to definitions. The grammar is not optimized for this. For example, `(pattern/identifier)` does not actually catch all …
=> Upgrade Python

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-javascript/test/base_syntax.js
When your function has a parameter named `undefined`, the parser makes it into an `(undefined)` node, distinct from all other parameters, and it doesn't get a `covalue`. This should probably be fixed in the parser, but in the interest of expedience (you'd be surprised/impressed/dismayed at how often this arises), we can work around the problem in the interim by just letting `(undefined)` sub in for a param—or, otherwise put: if it walks like a parameter, and it quacks like a parameter, it had better have a covalue like a parameter.
https://github.com/github/aleph/issues/3205
=> "undefined" can be the name of a parameter, too

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-javascript/test/base_syntax.js
JSX expressions containing comments as well as real actual expressions™ run into duplicate variables because the containing node now has multiple children, where the rules expected only one. Easy fix.
https://github.com/github/aleph/issues/3205
=> JSX expressions can contain comments

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-javascript/test/base_syntax.js
Decorators on classes (and their members) can be function calls and member expressions as well as variables, and thus need scopes propagated around like in other contexts. Unfortunately, they aren't `primary_expression`s in these positions for some reason I can't fathom, so we're forced to handle them uniformly with their handling in expressions and patterns via a single `(identifier)` rule.
This passes the tests, and is the minimal set of changes I was able to make which did so, but I have generally low confidence in it due to the rather broad nature of its changes and the spooky-action-at-a-distance nature of the grammar in general.
=> Class decorators can be (nearly) arbitrary expressions

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-javascript/test/base_syntax.js
JavaScript allows you to have `static` blocks of code in class scope which need to participate in name resolution. Easy enough.
=> Class static blocks

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-javascript/test/base_syntax.js
Computed property names can contain comments, which results in multiple matches despite the fact that there's only the one (expression) node in there that we care about.
=> Comments in computed property names

languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-javascript/test/base_syntax.js
(One of?) the last remaining identifiably non-spurious errors we're encountering :tada:
I really hate this approach to dealing with comments, but we can consider this the expedient solution at least.
=> Comments in export clauses

.github/workflows/ci.yml, languages/tree-sitter-stack-graphs-java/Cargo.toml, languages/tree-sitter-stack-graphs-javascript/Cargo.toml, languages/tree-sitter-stack-graphs-python/Cargo.toml, languages/tree-sitter-stack-graphs-typescript/Cargo.toml, lsp-positions/CHANGELOG.md, lsp-positions/Cargo.toml, stack-graphs/Cargo.toml, tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/README.md
Tweak the dependencies to prevent install problems such as those reported in #407.
The main change is to ensure that all `tree-sitter` have the same minor version, which prevents the Cargo resolver picking multiple versions for different crates.
The underlying problem is that there seems to be no way to teel Cargo that two transitive dependencies of the same crate should be the same version. However, if types from that crate are part of the API, things break if values are passed from one to the other. So far, the only solution I've found is to ensure that if the minor versions are the same, the resolver will only pick one patch version, thus ensuring the same version is used everywhere. (For non-zero major versions it might be enough if the major version is the same?)
Main changes:
- …
=> Dependency version cleanup

languages/tree-sitter-stack-graphs-javascript/Cargo.toml, languages/tree-sitter-stack-graphs-typescript/Cargo.toml, stack-graphs/CHANGELOG.md, stack-graphs/Cargo.toml, stack-graphs/README.md, stack-graphs/src/graph.rs, tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/Cargo.toml
I botched yesterdays release of `tree-sitter-stack-graphs` because it depended on unreleased changes in `stack-graphs`. Fix this be releasing both this time.
=> Release stack-graphs v0.13.0 and tree-sitter-stack-graphs v0.8.1

.github/workflows/publish-tree-sitter-stack-graphs-python.yml, languages/tree-sitter-stack-graphs-java/CHANGELOG.md, languages/tree-sitter-stack-graphs-java/Cargo.toml, languages/tree-sitter-stack-graphs-java/README.md, languages/tree-sitter-stack-graphs-javascript/CHANGELOG.md, languages/tree-sitter-stack-graphs-javascript/README.md, languages/tree-sitter-stack-graphs-python/CHANGELOG.md, languages/tree-sitter-stack-graphs-python/README.md, languages/tree-sitter-stack-graphs-typescript/CHANGELOG.md, languages/tree-sitter-stack-graphs-typescript/Cargo.toml, languages/tree-sitter-stack-graphs-typescript/README.md
After the updates to the library crates it makes sense to release the language crates as well. This will also give users who want to experiment the latest versions.
=> Release all language crates

languages/tree-sitter-stack-graphs-javascript/Cargo.toml, languages/tree-sitter-stack-graphs-javascript/src/stack-graphs.tsg
This updates the `tree-sitter-javascript` dependency to a release version, instead of a SHA dependency, making it releasable.
=> Update tree-sitter-javascript dependency to release version

languages/tree-sitter-stack-graphs-typescript/build.rs
- Error if one #dialect directive is nested in another
- Error if #dialect is missing #end at the end of file
=> Check for nested and unmatched directives

languages/tree-sitter-stack-graphs-typescript/rust/test.rs, languages/tree-sitter-stack-graphs-typescript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-typescript/test/jsx/jsx_core.tsx, languages/tree-sitter-stack-graphs-typescript/test/jsx/jsx_fragment.tsx, languages/tree-sitter-stack-graphs-typescript/test/jsx/jsx_namespace_name.tsx, languages/tree-sitter-stack-graphs-typescript/test/jsx/jsx_self_closing_element.tsx, languages/tree-sitter-stack-graphs-typescript/test/jsx/jsx_text.tsx
- Adds support for JSX elements: <Foo attr=val>{expr}</Foo> <Foo.Bar.Baz attr=val />
- The grammar uses nested_identifier for tags in the Foo.Bar.Baz form. It's the same symbol as what's used in namespaces: namespace Foo.Bar.Baz {}
As such it ends up producing a bit of junk (unconnected cliques) but I don't know if it can be fixed w/o tree sitter queries supporting matching only if under a specified ancestor.
- Unlike JavaScript, TypeScript requires variables to be declared. In JSX, <foo attr={x = 1}> {y = 2} </foo> is allowed if x, y are not in scope. They'll be created on first use. In TSX, this is disallowed which simplifies lexical_scope propogation compared to the JS TSG implementation.
=> Support JSX elements in TSX

tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/Cargo.toml, tree-sitter-stack-graphs/src/cli/index.rs
Running an `index` command in the CLI would abort if stack graph construction for one of the indexed failes failed.
This may be fine when debugging a spec, but too punitive for users, who would like as much partial information as possible in the database, even if some files are not covered by the spec, or bugs exist.
This PR changes the behavior to mark those files as failed (as we already do for files with parse errors) but continue with the remaining files.
Fixes #418.
Note that I've also bumped the version already, even though I'm not sure if I'll release right away or not.
In the past we'd only bump the version right before a release, which sometimes resulted in confusing situations when depending on the repo instead of released version.
The versions would still be comaptible, even …
=> Skip failed files during indexing instead of aborting the whole index operation

stack-graphs/src/graph.rs, tree-sitter-stack-graphs/CHANGELOG.md, tree-sitter-stack-graphs/src/cli/test.rs
When running tests, we would recompute the partial paths for the builtins for every test, even though they don't change.
This PR introduces a cache in the test runner that stores the partial paths in serialized form, and loads those into the test database. This takes ~30% of the TypeScript test time on my machine.
=> Cache partial paths for builtins when running tests

languages/tree-sitter-stack-graphs-typescript/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-typescript/test/modules/import-extension-js.ts, languages/tree-sitter-stack-graphs-typescript/test/modules/import-extension-none.ts, languages/tree-sitter-stack-graphs-typescript/test/modules/import-extension-ts.ts, tree-sitter-stack-graphs/src/functions.rs
Simple quick fix for #435, this can be evolved further but I believe will work in most currently broken cases.
=> fix: ignore .ts and .js extensions form imports

languages/tree-sitter-stack-graphs-python/src/stack-graphs.tsg, languages/tree-sitter-stack-graphs-python/test/root_path.py, tree-sitter-stack-graphs/src/cli/index.rs, tree-sitter-stack-graphs/src/cli/test.rs, tree-sitter-stack-graphs/src/lib.rs, tree-sitter-stack-graphs/src/loader.rs, tree-sitter-stack-graphs/src/test.rs, tree-sitter-stack-graphs/tests/it/builder.rs, tree-sitter-stack-graphs/tests/it/main.rs, tree-sitter-stack-graphs/tests/it/test.rs
Hello @hendrikvanantwerpen, this fixes #430.
This issue was that a symbol was poped for each part of the file path, but it was pushed (on import) only for each part of the import. (eg. it pushed Users, nohehf, module, foo and popped module, foo).
Languages like python needs knowledge about the "root path", as modules are resolved relative to the "input script" as stated here: https://docs.python.org/3/tutorial/modules.html#the-module-search-path
Here is my fix proposal, and I believe it could be useful for several other languages:
- introduces a `ROOT_PATH` global variable, that allows to compute the relative file path. This is particularly useful for interpreted languages like python that creates the modules paths relative to a base path.
- adds a test that reproduces the error as …
=> fix: python imports

languages/tree-sitter-stack-graphs-java/Cargo.toml, languages/tree-sitter-stack-graphs-java/src/stack-graphs.tsg
Version `0.20.2` of `tree-sitter-java` introduces the `condition` expression in `if_statement`:
```
(if_statement
-   condition: (parenthesized_expression)
+   condition: (condition)
consequence: (block)
alternative: (block)
)
```
It seems to be the only breaking change, all tests pass with this update.
If merged, this PR would close https://github.com/github/stack-graphs/issues/441
=> Update `tree-sitter-java` from `0.20.0` to `0.20.2`

languages/tree-sitter-stack-graphs-javascript/Cargo.toml
All tests passed with the newer version, no changes were needed
This would close https://github.com/github/stack-graphs/issues/449
=> Update `tree-sitter-javascript` from `0.20.3` to `0.20.4`

.github/workflows/publish-tree-sitter-stack-graphs.yml, languages/tree-sitter-stack-graphs-java/Cargo.toml, languages/tree-sitter-stack-graphs-javascript/Cargo.toml, languages/tree-sitter-stack-graphs-python/Cargo.toml, languages/tree-sitter-stack-graphs-typescript/Cargo.toml, stack-graphs/Cargo.toml, tree-sitter-stack-graphs/Cargo.toml
The previous PR removed explicit versions for in-repo dependencies. I expected that `cargo publish` would just replace the `path` dependency with the current version, but instead it complains and aborts.
This PR restores the version numbers where required. (It seems not required for dev dependencies, which I verified using a local `cargo publish --dry-run`.)
I also removed the `publish-npm` workflow job, which would have failed since the NPM package has been removed.
=> Fix dependencies to allow publish

tree-sitter-stack-graphs/src/lib.rs
Re-opening #466 as per [@hendrikvanantwerpen’s suggestion](https://github.com/github/stack-graphs/pull/466#issuecomment-2539585461).
=> Fix not defaulting to `Builder::file` for `FILE_PATH`.

languages/tree-sitter-stack-graphs-typescript/CHANGELOG.md, languages/tree-sitter-stack-graphs-typescript/Cargo.toml, languages/tree-sitter-stack-graphs-typescript/README.md
One version I forgot to increase.
=> Bump tree-sitter-stack-graphs-typescript version
